### ISSUE TITLE
[B] feat : 스터디 상세 페이지 내에 회차 목록에서 회차 참여자 프로필을 보여주는 기준 논의

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/groupstudy#102]
## 🐌 Summary
현재는 이렇게 5개의 StatusTag가 있습니다.
<img width="312" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/62997391/d01f9dc1-0898-4c16-9576-154dd18592e8">
<br>
이 중 ATTENDANCE, ATTENDANCE_EXPECTED, LATE인 경우에만 스터디 상세 페이지에서 회차 목록에 보여주도록 하면 될 거 같은데 어떻게 생각하시나요?
![image](https://github.com/rbgus2002/groupstudy/assets/62997391/889ec008-3c18-4927-93ae-3942419f38b8)

## 📝 To Do List
- [ ]

**Comment by Arkady1356** [comment]
결석을 표시 범위 제외한다는 의미이신가요?  흐으음

개인적으로는 
결석도 표시되어야 어느정도 자극도 되고, 
결석이더라도 과제를 할 수도 있을 것이고
상세 기록을 조회할 필요가 있을 수도 있으니!!

=> 모든 Status여도 다 보여져야 한다고 생각합니다!

**Comment by rbgus2002** [comment]
어.. 저희 결석은 사진과 같이 이 부분에서 프로필 사진을 안보여주기로 결정이 된 부분 아니었나요?? 
원래는 참여 여부에 따라서 태그 색상과 동일하게 프로필 사진에 색깔로 표시하려다가, 지저분할 거 같다는 이유로 결석만 아예 안뜨도록 빼기로 결정이 되어 노션에 적어뒀고 구현 완료한 상태입니다..!

<img width="371" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/62997391/0fd762db-4ad8-4e88-8efe-aff6b5ad2786">

제가 3회차에 결석을 한 경우, 이처럼 표시만 안되는 것이지 회차 상세보기에 들어갈 수 있습니다!
즉 [프로필 사진 리스트의 의미 == 회차 참여 여부] 라고 생각했습니다..!

**Comment by rbgus2002** [comment]
다시 돌리는 것이야 금방 할 수 있긴 합니다!!
Status에 상관없이 다 보여주면 해당 부분에 참여자 프로필 리스트를 넣는 것에 의미가 퇴색 되는 것 아닌가 싶습니다..!

**Comment by Arkady1356** [comment]
아하 그런 의미로 말씀하신거였군요

>  ATTENDANCE, ATTENDANCE_EXPECTED, LATE인 경우에만 스터디 상세 페이지에서 회차 목록에 보여주도록

에서 회차 목록 자체에서 회차를 안보여준다고 이해했었습니다 하하
참여자 리스트에서 안보여지는 것이라면 매우 굳굳입니다. 제가 생각한바와 일치합니다!

**Comment by rbgus2002** [comment]
휴휴휴 그렇군요 제가 설명을 본문에 잘못한 거 같아요 흑흑 감사합니당

**Comment by rbgus2002** [comment]
그러면 말씀 드린 대로, 출석예정, 출석, 지각만 참여자 프로필 리스트를 띄우도록 하겠습니다!
