### ISSUE TITLE
[F] feat : 스터디 멤버 조회 API 수정 요청

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#106]
방장을 위임할때 확인을 목적으로
"$nickname에게 방장을 위임할까요?" 물어보려고 하는데
nickname정보가 필요하더군요

nickname을 추가해주세요
(혹은 userId -> nickname조회 api를 만들어주세요!)

## 🐌 Summary
GET /api/studies/participants/summary 에
nickname정보도 추가해주세요

## 📝 To Do List
- [x]  GET /api/studies/participants/summary에 nickname 추가

## 📷 스크린샷(선택)
<img width="205" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/3ed0bcdf-23f1-4d49-a153-10d3968dee5e">

**Comment by rbgus2002** [comment]
완료했습니다!
