### ISSUE TITLE
공지사항 상세 조회 시 읽음 표시에 대한 기획 논의 

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/groupstudy#11]
재우님 하이
현재 아래 이미지와 같이 앱 개발이 되어있는 걸로 알고 있습니다.
![image](https://github.com/rbgus2002/groupstudy/assets/62997391/162622a2-b868-4d55-9b23-b65cce6630d4)

질문하고자 하는건 접때 저희 지하철 타면서 공지사항 읽음처리와 관련해서 논의했던 부분의 연장선 입니다.

1. 공지사항 읽음 부분을 길게 눌렀을 때 읽음 처리 한 인원의 프로필 이미지를 보여주기로 한 걸로 기억하는데 맞는지 궁금합니다~

2. 맞다면 공지사항 상세보기 시에는 공지사항 읽음 처리를 한 인원의 수만 client로 response 해드리면 되는지 궁금합니다~

답변 부탁드립니다~

**Comment by Arkady1356** [comment]
아하 안녕하세요!
1. 넵 맞습니다
2. 넵 맞습니다.

근데 방금 다시 생각해 보니까, 꾹 눌렀을때 그때 프로필 이미지들을 가져오고 보여주면 좀 늦지 않을지 걱정되네요
(1) 지금처럼 1) 상세보기 기본 정보, 2) 프로필 이미지들을 따로 따로 받는게 좋을지
(2) 수정해서 1) 상세보기 기본 정보 + 프로필 이미지들을 한번에 받는게 좋을지
잘 모르겠네요...ㅋㅋ.. 
(2)로 했을때 Cost가 좀 크려나? (1)로 했을땐 지연이 어느정도 이려나..

**Comment by rbgus2002** [comment]
제 생각엔 충분히 지연 시간이 적을 것으로 예상하는데, 일단 원래 말씀 나눴던 대로 구현하면 좋을 거 같습니다~

++ 질문 추가드립니다.
3. 공지사항 상세보기 시에 상단 고정되어있는 공지사항은 별도의 표시를 줄까요? 어떻게 생각하시나요

**Comment by Arkady1356** [comment]
넵 기존대로 구현해보고 지연이 심하다 싶으면 그때 다시 한번 이야기해보도록 하죠!!
---
3. 음 저도 그 부분에 대해 생각을 해보았는데 없는 것이 맞다는 결론을 내렸었습니다!! 고정이라는 것이 리스트 ... [더보기]

**Comment by rbgus2002** [comment]
어..? 저만 이상하게 보이나요?? [더보기]???

**Comment by Arkady1356** [comment]
안녕하세요 규현님!

공지사항 상세 조회 읽음 표시 API와 관련해서 요청사항 드립니다.

현재 반환값으로 읽음/안읽음 여부만 리턴해주고 있는데요,
추가로 몇명이 읽은 상태인지도 리턴해주시면 감사하겠습니다. ㅎㅎㅎㅎ
