### ISSUE TITLE
공지사항 상세 조회 시에 댓글 개수 표시 여부 

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/groupstudy#13]
[GET /notices] API에 관한 내용입니다. (공지사항 상세 조회)

공지사항 상세 조회 시에 댓글 개수도 나타내면 좋겠다는 생각을 했습니다. 어떻게 생각하시나요?
대략적인 디자인은 블라인드 어플을 참고해주세요.

**Comment by Arkady1356** [comment]
너무 좋습니다 !! 같이 주시면 제가 디자인적으로 잘 고려해서 추가할게요 =)

**Comment by rbgus2002** [comment]
공지사항 상세 조회 시에 댓글 개수도 포함해서 response 받을 수 있도록 수정 완료해서 배포했습니다.
반영하시고 issue close 부탁드립니다~~
