### ISSUE TITLE
공지사항 읽음/안읽음 체크 API의 reponse 수정 관련 요청사항 질문

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/groupstudy#14]
[PATCH /notices/check] API 관련 이야기 입니다!

"안녕하세요 규현님!
공지사항 상세 조회 읽음 표시 API와 관련해서 요청사항 드립니다.
현재 반환값으로 읽음/안읽음 여부만 리턴해주고 있는데요,
추가로 몇명이 읽은 상태인지도 리턴해주시면 감사하겠습니다. ㅎㅎㅎㅎ"

라고 재우님이 요청해주셨습니다.
아마도 읽음/안읽음 여부를 return하는 이유와 마찬가지로 신뢰성을 높이고자 요청해주신 사항이라고 생각합니다.

하지만 사용자가 해당 버튼 연타,... 하는 경우 등 해당 기능의 신뢰성을 높이려고 몇명이 읽은 상태인지 알기 위해 쿼리를 날리는 건 약간 과하지 않을까 싶은데 어떻게 생각하십니까???

**Comment by Arkady1356** [comment]
아하 쿼리의 코스트가 큰가요? 저는 그냥 클래스 마냥 변수 return 바로 할 수 있는 정도인 줄 알았습니다 ! ! 말씀 하신것 처럼 cost가 크다면 구지 추가 안해도 상관 없을 것 같아요 ㅎㅎ

**Comment by rbgus2002** [comment]
쿼리 자체는 크지 않지만 이런 부분이 하나씩 누적되었을 때가 걱정되어서 말씀 드렸습니다 ㅎㅎ 그러면 당장은 안넣는 걸로 해요~
