### ISSUE TITLE
스터디 상세 보기의 공지 사항 3개 API 요청

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#15]
안녕하세요 규현님,
다음 작업으로 스터디 상세 보기에서 볼 수 있는 공지 사항 3개를 반환해주는 API를 요청드리겠습니다. 참고하실 사진 보내드립니다~

<img width="460" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/7fd9e0a9-c494-4622-b0d1-cb4eac6329b2">

**Comment by rbgus2002** [comment]
오우 굳굳 사진 첨부해주셔서 바~로 이해했습니다 ㅎㅎ 감사합니다

기획적으로도 협의가 필요할 거 같습니다.
현재 공지사항 목록 가져오는 API에서 상단 고정되어있는 공지사항을 우선순위로 최근순으로 가져옵니다.
공지사항 목록 가져오는 API와 마찬가지로 상단 고정 공지사항 포함해서 최근순으로 3개만 딱 자르면 될까요?

**Comment by Arkady1356** [comment]
음~ 방금 생각해보았는데 그게 맞는 것 같네요. 상단 고정 포함 상위 3개로 합시다!!

**Comment by rbgus2002** [comment]
API 개발 후 배포 완료했습니다. 확인하시고 issue close 해주세요~

**Comment by Arkady1356** [comment]
규현님! 질문 있습니다
현재 공지 사항 요약 리스트를 받는 API가 두가지 있는것으로 알고 있습니다.
1) (get)notices/list?studyId=1
2) (get)notices/list/limited?studyId=1

혹시 이런 느낌의 흐름은 이상할지 궁금합니다 (한번 이야기 나눴던것 같은데 답변이 기억이 안나네요ㅎ.. 문서화도 시킬겸 이슈 날립니다)

---
전달 인자 :
1) 스터디 아이디,
2) 시작 번호,
3) 길이,

: ${스터디 아이디}의 공지 사항들 중 ${시작 번호}번째 순번부터 $길이 개의 '공지 요약 리스트' 반환

=> 하나의 API로 전달 인자를 달리하는건 어떤가요?
전체 리스트를 조회할 때에도 다음과 같이 활용(비용 절감)할 수 있을 것 같아요
  처음 : 0번째 부터 10개 로딩 (n = 10)
  아래로 스크롤 : n번째 부터 10개 추가 로딩 (n += 10)

규현님의 견해가 궁금합니다 !!

**Comment by rbgus2002** [comment]
와우 놀랍네요... 실제로 말씀해주신 대로 구현하는 것이 맞습니다,, 
페이징을 해야하는데 학습하기 귀찮아서 그랬습니다... 일단 붙이신거면 제가 이 이슈 close 안하고 추후에 바꿔도 될까요 ㅋㅋ 시간,... 좀 있을 때...

**Comment by Arkady1356** [comment]
ㅋㅋㅋㅋ 넵넵 확인하였습니다!! 나중에 우선순위 높은 일들을 우선적으로 처리한 후에 다시 건들이는 걸로 알고있겠습니다 !!
