### ISSUE TITLE
"공지사항 상세 조회"시 "본인의 읽음 여부" 추가 요청

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#16]
안녕하세요 규현님!
공지사항 상세 조회 API (notices?noticeId)에서 추가 요청사항 있어서 Issue 날려요

사용자(본인)이 해당 공지를 읽음 표시했는지 안했는지 여부가 필요하더군요

이 과정에서 사용자 아이디도 필요하시겠네요 
이쯤 되면 "읽음 여부 버튼"에서 호출하는 정보에 대한 API를 별도로 빼야하나 싶을정도네요 ㅋㅋ

<img width="420" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/5d1e751c-f26c-44cb-8db6-51076506ca37">

**Comment by rbgus2002** [comment]
(카페인의 위험성을 잘 아시면서 하루에 2잔 이상 꾸준히 드시는 모습, 보기 좋습니다 ㅎㅎ)

요청해주신 대로 
1. 공지를 읽음 여부도 함께 response 할 수 있도록 추가하겠습니다.
2. request 날릴 때 userId (사용자 아이디)도 함께 날릴 수 있도록 수정하겠습니다.

수정하고 말씀 드릴게요~

**Comment by rbgus2002** [comment]
fix (수정사항) 이라는 label 만들었습니다. 참고해주세요~

**Comment by rbgus2002** [comment]
수정 완료해서 배포했습니다! 확인 하셔서 반영하고 이슈 닫아주세요
