### ISSUE TITLE
백로그 유효성에 관한 논의

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/groupstudy#17]
프로젝트를 진행할 때 개발해야할 기능, 우선순위 등을 Backlog를 통해 효율적으로 관리할 수 있다고 들었습니다.
위의 이유로 구글 시트를 통해 백로그를 작성했는데 제대로 사용하지 않고 있기 때문에 효율성을 느끼지 못하고 있어서 아쉽습니다..!

지금 어느 페이지까지 개발이 되어있는지, 진행상황을 잘 모르고 있는데 백로그를 적극적으로 사용해서 소통 없이도 바로 파악할 수 있도록 해보는 건 어떨까요?

사실 백로그가 전체적으로 퍼포먼스를 높이는 지에 대해서는 잘 모르겠습니다. 아직 제대로 사용해본 적이 없기 때문에 잘 모르는 만큼 일단은 한번 백로그 열심히 작성해보는 것도 좋을 거 같습니다! 어떻게 생각하시나요 ㅎㅎ

**Comment by Arkady1356** [comment]
헉 .. 백로그의 존재를 잊고 있었네요. 오늘부터라도 다시 백로그를 작성하도록 하겠습니다!!
한편으로는 백로그 작성할때 약간 어디에 어떤 내용을 적어야할지가 모호할때도 있었던 기억이네요.
아무튼 그런거는 제쳐두고 지금 하는 큼직 큼직한 것이라도 추가해 놓도록 하겠습니다 !!
