### ISSUE TITLE
스터디 상세 보기의 스터디 요약 정보 API 요청 

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#18]
안녕하세요 규현님!
새로운 작업 요청을 기다리시는 것 같아서 새로운 요청 드려요
사진의 상단에 위치한 스터디 요약 정보를 전달해주는 API를 요청드립니다!
프로필 사진, 스터디 고유 색상, 스터디 이름 및 스터디 설명, 스터디 아이디가 필요하겠네요
부탁드리겠습니다~

![image](https://github.com/rbgus2002/groupstudy/assets/86937581/ea74741a-4eb1-4889-bf90-42ad79341952)

**Comment by rbgus2002** [comment]
"새로운 작업 요청을 기다리시는 것 같아서" ?????????????????????????????????????????????????ㅠㅠㅠㅠ

**Comment by rbgus2002** [comment]
만들었습니다. 확인하고 반영하시면 close issue 해주십시오,,


---- 수정----
스터디 고유 색상은 각자마다 다르게 보일 수 있도록 테이블을 설계해놓았습니다. 그래서 일단 해당 부분은 제외하고 api 설계했는데 추후에 관련해서도 다시 말씀 나눠보면 좋을 거 같습니다

**Comment by Arkady1356** [comment]
저는 고유 색상을 스터디 별로 정해지는 것으로 생각하고 있었습니다 !! (사용자가 설정하는 것이 아닌, 스터디를 생성할때 스터디만의 고유 색상을 가지는 것)
오늘 중으로 API연결하고 이슈 Close 하겠습니다~

**Comment by rbgus2002** [comment]
저는 개인적으로 스터디 별로 고유 색상을 부여했을 때 얻는 이점이 없다고 생각합니다.
각자가 알아서 색상 커스텀 하도록 만드는 것이 좋지 않을까요? 다른 의견 있으시면 말씀해주세욥~

**Comment by Arkady1356** [comment]
오호 듣고보니 맞는 말씀입니다
말씀하신 것처럼 개인별로 색상을 지정할 수 있는것으로 알고 있겠습니다
근데 방금 적으면서 생각해 보았는데 해당 색상에 대한 세팅은 어디에 넣어야 적절할까요...?
괜히 복잡해지는게 아닌가 우려를 표합니다 ㅋㅋㅋ ㅋㅋㅋ

**Comment by rbgus2002** [comment]
음 색상에 대한 세팅은 메인화면에서만 색상 설정 가능하도록 만들면 어떨까요?
늦게 comment 달아서 ㅈㅅㅈㅅ해요 잘 사시죠 재우님..?

<img width="996" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/62997391/96345963-c36a-4658-b201-640515a61223">

**Comment by Arkady1356** [comment]
ㅋㅋ 잘지내고 있었습니다!!
음 그럼 저 스터디의 원 프로필을 눌렀을때 색상을 바꿀 수 있도록 해볼까요..!
별도로 색상 바꾸는 API 넣어주시면 추후 적절히 넣어보도록 하겠습니다 ~

**Comment by rbgus2002** [comment]
db 내에서 16진수 값으로 색상 저장해야할 거 같은데 어떻게 생각하시나요

**Comment by Arkady1356** [comment]
넵 너무 좋습니다!

0xAARRGGBB의 형태이면 좋을 것같습니다.
AA : 불투명도
RR : Red
GG : Grean
BB : Blue
이때 알파벳은 대소문자가 상관없어 보이긴 하지만, Fluuter에서는 소문자가 deafult인듯 합니다.

ex) { Blue : 0xff2196f3 }

추가로 질문 있으시면 말씀주세요 ~

**Comment by rbgus2002** [comment]
해당 형태로 넘겨드리면 플러터가 알아서 색상으로 변환해주는건가요?!

**Comment by rbgus2002** [comment]
오 딱 궁금했던 부분이었습니다 친절하셔라 감사합니다~~

**Comment by Arkady1356** [comment]
아 위에서 잘못된 표현을 했었네요...ㅎ 위에 제가 작성한 Color(...) 에서 인자로 문자열인 것처럼 적어두었는데 16진수로 표현되는 정수값이 들어가는게 맞습니다..ㅎ 잘못 전달드려 죄송합니다 !! ㅠㅠㅠ

Color("0xff2196f3"); // (X)
=>
Color(0xff2196f3); // (O)

**Comment by rbgus2002** [comment]
zzzz저한텐 똑같습니다 쨌든 ㄱㅅㄱㅅ~

**Comment by rbgus2002** [comment]
색상 변경하는 부분은 따로 issue 날려 API 개발했습니다.
해당 issue 건 완료 됐으면 close 해도 될까요?

**Comment by Arkady1356** [comment]
넵 혹시 빠트리는 부분있을까 싶어 Close 안하고 있었으나, 검토해본 결과 문제 없습니다 !! Close 하겠습니다.
