### ISSUE TITLE
공지사항 상세 보기에서의 공지 사항 삭제하기 및 댓글 삭제하기

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#19]
안녕하세요 규현님!
"새로운 작업 요청"을 기다리시는 것 같아서 또 추가로 새로운 요청 드립니다.

1) 공지 사항 게시물을 삭제하는 기능과
2) 댓글을 삭제하는 기능

두 가지의 기능을 요청드립니다 =)
![image](https://github.com/rbgus2002/groupstudy/assets/86937581/6b8b682b-3410-4abb-93d8-12a2e09a40e3)

**Comment by rbgus2002** [comment]
ㅋㅋ... 아.. 네.. 얼른 할게요..

**Comment by rbgus2002** [comment]
1. 공지사항 삭제 API 개발 완료했습니다.
2. 댓글 삭제 API 개발 완료했습니다.

**Comment by Arkady1356** [comment]
공지사항 삭제 API를 연결하였습니다.
연결하는 과정에서 2개의 질문이 생겼습니다!!
1) 추후에 삭제 권한에 대해서도 생각해 볼 필요가 있을 것 같아요! 
2) 삭제된 게시물(공지사항)의 데이터는 남아있나요 아니면 아예 지워지나요? => 삭제된 게시물에 대해 접근시 별도의 관리가 이루어지나요? 음 그냥 올바르지 않은 공지사항 접근에 대해서 삭제된 게시물로 취급하는게 맞을까요 흐으으음..

**Comment by rbgus2002** [comment]
1. 일단 기능 구현은 하고 삭제 권한에 대해서 말씀 나누면 좋을 거 같습니다. API 연동만 해놔 주시면 감사하겠습니다!
미리 생각해봤는데 스프링 시큐리티 활용해서 하면 좋을 거 같은데 시간이 없기 때문에 추후에 비즈니스 로직적으로 해결놓으려고 합니다. << 사실 프론트 쪽에서 아실 필요는 없는 정보이긴 합니다!! 
나중에 한 번 얘기해봐요~ remind 할 수 있도록 issue 따로 날려놓겠습니다!

2. 삭제된 게시물은 deleteYn 이라는 flag로 구분하기 때문에 실제로 DB 내에서 삭제하는 것은 아닙니다. 스프링의 기능을 이용해서 모든 공지사항 관련 API에서 자동으로 삭제 여부를 검사합니다!
따라서 삭제된 데이터는 삭제되었다고 메세지 날아가고, 잘못된 접근이면 "존재하지 않는 공지사항입니다." 등 간단한 정보를 내려줄겁니다 ㅎㅎ.
충분히 대답이 되었으면 좋겠지만 더 논의가 필요하다고 느껴지시면 따로 issue 날려주시면 감사하겠습니다!

**Comment by Arkady1356** [comment]
와 어제 너무 졸려서 졸면서 쓴거라 두서없이 썼었는데 좋은 답변주셨네요 ㅋㅋ ㅋㅋㅋ 감사합니다!! 

1. "사실 프론트 쪽에서 아실 필요는 없는 정보이긴 합니다"가 가장 인상 깊은 구절이네요 ㅎㅎㅎ
2. 역시 deleteYn 있을 것 같았습니다!! 해당 내용도 반영하도록 하겠습니다 :-)

**Comment by rbgus2002** [comment]
넵 나머지 API 연동해주시고 close issue 부탁드립니다~

**Comment by Arkady1356** [comment]
댓글 삭제 API도 연결 하였습니다.

그런데 대댓글이 있는 댓글을 삭제할 경우 

댓글 : ~~~
댓글 : 삭제된 댓글입니다
ㄴ 대댓글 : ~~~
ㄴ 대댓글 : ~~~

과 같이 표시하기로 했던 것으로 기억하는데, 
현재는 대댓글이 있는 삭제된 댓글이 함께 반환되지 않는 것 같습니다 !!
한번 이야기 나누면 좋을 것 같습니다.

**Comment by rbgus2002** [comment]
아 그렇군요!! 기획적으로 제가 이해한 바는 이렇습니다.
1. [삭제된 댓글 && 대댓글 존재O] => 댓글은 삭제된 댓글입니다, 대댓글들은 정상 표시
2. [삭제된 댓글 && 대댓글 존재X] => 아예 보이지 않음
3. [삭제되지 않은 댓글 && 삭제된 대댓글 존재] => 댓글 정상 표시, 삭제된 대댓글은 삭제된 댓글입니다.

위 기획이 맞다면 다음 두가지 방식이 있을 거 같은데 프론트 관점에서 어떤 방식을 선호하시나요?
1. 모든 댓글에 대해서 삭제 여부를 포함해서 넘겨드리고 프론트에서 전적으로 관리하는 방식
4. 백에서 추가적인 필터링을 거쳐, 아예 표시되지 않아도 되는 (ex. 삭제된 댓글 && 대댓글 존재X) 댓글들은 아예 안보내고 표시되어야 하는 댓글들은 삭제 여부 포함해서 넘겨드리는 방식
이해 안되시면 좀 더 자세히 설명해보겠습니다~ 읽어보시고 답변주세요

**Comment by Arkady1356** [comment]
넵 저도 동일하게 이해하고 있습니다!! 완전 이해잘되게 정리해주셨네요 !! 굳굳

흠 2.번이 좋을 것 같아요 !!!

혹시 추가로 삭제된 댓글의 내용을 조작해서 보내주는 것도 가능할 까요?
<img width="717" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/09525c3d-e4bf-4a38-83e5-a0867becc9e5">

위의 사진 처럼
사용자 명 : "(삭제됨)"
내용 "삭제된 댓글 입니다."
로 보내주실 수 있나요!? 

물론 삭제 여부를 통해 프론트에서 관리할 수 있지만, 보안 상의 이유로 삭제된 내용이 클라이언트에게 전달되면 안될 것 같아 질문 드립니다!!

**Comment by rbgus2002** [comment]
그럼 서버 단에서 전적으로 처리하고 보낼 수 있도록 로직 수정하고 말씀 드리겠습니다!

**Comment by rbgus2002** [comment]
만들었는데 확인해주쇼

**Comment by Arkady1356** [comment]
해당 부분에 대해서도 생각해보았는데,
... 을 누르면 사진과 같이 박스가 열리며 선택할 수 있게 되어있습니다.
<img width="388" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/09c0502d-5fe5-4ef9-ab25-2b0c278b3b3a">
'신고하기'와 같은 다른 항목이 있다면 말씀하신것 처럼 '삭제 버튼'자체를 없앨 수 있겠지만,
아직 '신고하기'와 같은 다른 항목에 대해서는 이야기를 나누지 않은 상태라 '삭제 버튼'만 존재한다는 가정하에서,
 삭제 시도 및 실패, 실패 메세지로 "본인이 작성한 ~"을 반환하는 것이 어떨까 생각해 보았습니다 !!

**Comment by rbgus2002** [comment]
댓글에 존재하는 사용자id와 본인의 사용자id가 일치하는 경우만 ...를 보여주는 건 어떠세요?????

**Comment by Arkady1356** [comment]
음 일관성이 떨어지지 않을까 생각이 듭니다..!! 
ㅋㅋ 아니면 '프로필 보기'를 추가하고, 본인일때만 '삭제하기'보여지도록 해볼까요

**Comment by rbgus2002** [comment]
좋은 거 같습니다! 그러면 모든 댓글에 ...는 있는거겠네요!

**Comment by Arkady1356** [comment]
ㅋㅋ 넵넵 좋습니다 그럼 이야기드린대로 진행하겠습니다!!

**Comment by rbgus2002** [comment]
좋습니다!

**Comment by rbgus2002** [comment]
넵 알겠습니다~!

**Comment by Arkady1356** [comment]
규현님!! 댓글 삭제는 문제없이 마무리 하였으나,

공지 사항의 경우 삭제 유효성 검사를 위해
1) 작성자의 userId
2) 사용자의 userId
를 비교할 필요가 있는데,

현재 작성자의 nickname만 반환되고 있습니다!!

GET notices?noticeId=?&userId=?
에서 추가적으로 userId 반환을 요청드립니다 !!
