### ISSUE TITLE
RoundInfo class의 분할 관리

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#2]
안녕하세요 규현님 RoundInfo Class 세분화 요청 드립니다.

현재 RoundInfo class는 
![image](https://user-images.githubusercontent.com/86937581/236659332-96dbfcbb-2e23-4bde-a32d-d4913599ed6b.png)
를 표현하고 있는데,

RoundInfo는
![image](https://user-images.githubusercontent.com/86937581/236659347-d3ff102e-0747-4887-8e5b-d3ecc1b899db.png)
단위로 만들어지고, RoundInfoPanel에서 RoundInfo와 UserListButtons를 가지는 형태로 만들어야 할 것 같습니다.
추가로 사진과 같이 Tag가 들어갈 수 있는 공간이 마련되어 있어야 합니다 그리고 '>'기호도 RoundInfo에서 가지기 보다는 이용할때 별도로 옆에 버튼을 추가할 수 있는 형태이면 좋을것 같습니다! 

요약
1. RoundInfo와 RoundInfoPanel을 구분하고, 세분화 해주세요
2. RoundInfo에 Tag가 들어갈 수 있는 장소를 마련해 주세요
3. '>'기호는 별도로 추가하도록 하게 해주세요

감사합니다

**Comment by rbgus2002** [comment]
ㅇㄴㅁㅇㄴㅁㅇㅁㄴ

**Comment by rbgus2002** [comment]
추후에 말씀하신 대로 수정해서 반영하겠습니다~
다음에는 issue 날릴 때 첫 부분에 [F] 혹은 [B]로 앱인지 서버인지 구분 부탁드립니다!

**Comment by Arkady1356** [comment]
네 앞으로는 [F] | [B]를 표기하도록 하겠습니다 감사합니다 =)

**Comment by rbgus2002** [comment]
요약 2.
=> 해당 tag는 회차별로 사용자 본인이 갖는 Tag라고 알고 있는데 맞나요?
=> 해당 위치의 tag는 반드시 1개만 올 수 있도록 하면 될 거 같은데 어떻게 생각하시나요?

**Comment by Arkady1356** [comment]
=> 해당 tag는 회차별로 사용자 본인이 갖는 Tag라고 알고 있는데 맞나요?
: 네 맞습니다. "홈 화면"에서 해당 회차의 참석 예정 여부를 지정할 때 사용될 태그 공간입니다. (*프로토타입 홈화면을 참고해 주세요)

=> 해당 위치의 tag는 반드시 1개만 올 수 있도록 하면 될 거 같은데 어떻게 생각하시나요?
: 네 좋습니다/맞습니다. 단 하나의 Tag만 들어갈 수 있는 자리이면 됩니다. "홈 화면" 이외의 Route에서는 Tag가 공란으로 이용된다는 점도 고려해주시면 감사하겠습니다. (Nullable)
