### ISSUE TITLE
회차 정보 가져오기 API 요청 

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#21]
안녕하세요 규현님!

"회차 정보 리스트"를 가져오는 API를 요청드립니다!
두 개의 페이지에서 회차 정보를 필요로 합니다.

1) '스터디 상세 보기'에서의 회차 정보 리스트
2) '회차 상세 보기'에서 상단의 회차 정보

사진을 하단에 첨부해두었습니다!!

1) '스터디 상세 보기'에서는 여러 회차에 대한 정보를 리스트로 필요로하고,
참여자들에 대한 정보도 추가로 요청됩니다. (원형 사진 리스트)
참여자들의 정보는 다음을 내포합니다
#Case 예정된 회차 : 해당 회차의 참석 예정 여부의 색상과 이번 숙제의 진행 정도(%)가 필요합니다.
#Case 종료된 회차 : 회차에 참석/지각/결석/불참 등의 여부가 색상으로 표시되고, 최종 숙제 진행 정도(%)가 필요합니다.
(결국은 [ 색상, 진행정도[0:1] ]의 리스트가 필요함)
추가로 개인 프로필로 접근을 위한 사용자 아이디도 필요로 합니다
 
<img width="424" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/098c7052-c326-469e-b417-1f44cabc6fc8">

1) '스터디 상세 보기'에서의 회차 정보 리스트

<img width="409" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/22260603-052f-4de9-8f45-ea7e7b7c1296">

2) '회차 상세 보기'에서 상단의 회차 정보

논의가 필요한 부분 있다면 말씀해 주세요 !!

**Comment by rbgus2002** [comment]
1. 스터디 상세 보기'에서의 회차 정보 리스트
2. 회차 상세 보기'에서 상단의 회차 정보

두 개를 같은 API로 만들고 image flag 를 두어 true이면 프로필 이미지도 반환하도록 만들어 하나의 API를 활용하는 건 어떠신가요?

**Comment by rbgus2002** [comment]
넘모 바쁘네요,.. 저에게 약간의 시간을 주십시오... 얼른 하겠습니다..💪🏼🤜🏼

**Comment by rbgus2002** [comment]
숙제 진행 정도(%)의 정보는 구현하기 생각보다 까다롭네요. 일단 숙제 진행 정도(%)만 제외하고 (회차 정보 리스트 AND 참석/지각/결석/불참 등)의 여부를 보내드려도 될까요? 동의 해주세요.. '해줘'

**Comment by rbgus2002** [comment]
3초 이상 답이 없으셔서 동의하신 걸로 간주했습니다!!
숙제 진행 정도 제외하고 회차 정보 가져오도록 API 개발 완료했습니다~

**Comment by Arkady1356** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ 이건 또 뭐람 넵넵 동의했던것으로 하겟습니다
오늘 중으로 확인해보고, 연결드린 이후에 말씀 드릴게요 !

**Comment by rbgus2002** [comment]
넵~~~

**Comment by Arkady1356** [comment]
에고 바뻐서 붙이는게 좀 늦었네요..ㅎ
API는 잘 연결되었습니다~
다만 위에서 이야기한 image flag가 빠진것 같아요...! 확인 부탁드립니다 ~

**Comment by rbgus2002** [comment]
> 1. 스터디 상세 보기'에서의 회차 정보 리스트
> 2. 회차 상세 보기'에서 상단의 회차 정보
> 
> 두 개를 같은 API로 만들고 image flag 를 두어 true이면 프로필 이미지도 반환하도록 만들어 하나의 API를 활용하는 건 어떠신가요?

다시 확인해보니 윗부분에서 잘못된 논의가 있는 거 같아 말씀드립니다.
1번의 경우는 회차 목록이고 2번의 경우는 특정 회차이니 API를 분리해야하지 싶습니다.
1번은 GET /rounds/list이고, 2번은 GET /rounds/details을 활용하면 어떨까요?

**Comment by rbgus2002** [comment]
> 에고 바뻐서 붙이는게 좀 늦었네요..ㅎ API는 잘 연결되었습니다~ 다만 위에서 이야기한 image flag가 빠진것 같아요...! 확인 부탁드립니다 ~
> 
> [ADDED] 추가로 사진 1에서 처럼 리스트로 주실때, 내림차순으로 주시면 감사하겠습니다!! (null 우선 + 내림 차순)
> 
> <img alt="image" width="200" src="https://user-images.githubusercontent.com/86937581/259060414-60deb62b-0424-4bcd-9cc8-3d1a92243003.png">  
> 사진을 보시면 현재는 (오름차순 + null 차선)이라 역순으로 나열됨을 확인할 수 있습니다!!

null 우선, 약속 시간 기준 내림차순으로 변경해서 작업하고 해당 issue에 다시 댓글 남기겠습니다!

**Comment by Arkady1356** [comment]
넵넵 두가지로 나누어 진행하는 것으로 알고 있겠습니다

---
넵넵 감사합니다!! 반영되는 대로 이슈 날리겠습니다~

**Comment by rbgus2002** [comment]
> 넵넵 두가지로 나누어 진행하는 것으로 알고 있겠습니다

1번은 GET /rounds/list이고, 2번은 GET /rounds/details을 활용하도록 개발 완료했습니다.
1번의 경우에는 변경사항 없고, 2번의 경우는 변경사항 있습니다.  GET /rounds/details는 다음처럼 수정되었습니다~
기존에는 detail만 response 했는데, 이제는 roundId 및 약속정보 (studyPlace, studyTime, isPlanned)도 함께 response 합니다!
<img width="412" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/62997391/acf924a0-ea31-48ee-90af-2582b1a596eb">

**Comment by rbgus2002** [comment]
> 2번은 문제 없이 연결하였습니다~ 1번도 연결되면 말씀드리겠습니다
> 
> ㅋㅋ 그리고 이제 할일 없으시면 %도 구현해주시면 감사하겠습니다 ^_^

숙제 진행정도는 다음처럼 이해하고 있는데 맞나요?!
1. 회차 별로 숙제 진행정도를 갖는다.
2. (check한 태스크 개수 / 전체 태스크 개수) 로 계산한다.
3. 종료된 회차도 태스크를 check 하면 숙제 진행정도가 바뀐다.
맞을까욤

**Comment by Arkady1356** [comment]
1번도 다시 연결하였습니다. 1번 2번 연결 모두 완료하였음을 알립니다.

---
1. 맞습니다
2. 맞습니다
3. 넵 맞습니다. 다만, 종료된 회차의 태스크 check는 못하도록 하고 싶네요..!
  전에도 이런 대화를 했던 것으로 기억합니다!! -> Front단에서 out-date -> Check 못하게 할까요 

---
와 gitify 짱편하네요 하하

**Comment by rbgus2002** [comment]
> 1번도 다시 연결하였습니다. 1번 2번 연결 모두 완료하였음을 알립니다.
> 
> 1. 맞습니다
> 2. 맞습니다
> 3. 넵 맞습니다. 다만, 종료된 회차의 태스크 check는 못하도록 하고 싶네요..!
>    전에도 이런 대화를 했던 것으로 기억합니다!! -> Front단에서 out-date -> Check 못하게 할까요

음 그러게요 그 부분은 추후에 다시 논의해봐도 좋을 거 같습니다..!

**Comment by rbgus2002** [comment]
> 1번도 다시 연결하였습니다. 1번 2번 연결 모두 완료하였음을 알립니다.

현재 미구현 상태이긴 하지만 미리 연결해놓으시라고 taskProgress라는 숙제 진행정도 필드 함께 response 하도록 추가했습니다. 필드명 자체는 바뀌지 않을테니 구현 여부랑 상관없이 붙여놓으시면 될 거 같아요!

<img width="276" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/62997391/6dd9271e-e6f0-43d3-9fdd-b9f01a74ed95">

**Comment by Arkady1356** [comment]
넵 말씀하신 대로 연결해두었습니다. Issue에 Later 달아 둘게요~

**Comment by rbgus2002** [comment]
숙제 진행정도 구현 완료해서 issue close 하겠습니다!
