### ISSUE TITLE
회차 상세 보기의 세부 기록 가져오기/수정 API 요청

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#22]
안녕하세요 규현님!!
'회차 상세 보기'의 세부 기록 (Detail Record)와 관련된 API 요청드립니다. 
1) '세부 기록' 가져오는 API
2) '세부 기록' 수정하는 API 
를 요청 드립니다 !!

우선 '세부 기록'은 String 자료형으로만 입력 받고, 저장하고 보여주는 것으로 이해하고 있었습니다!
나중에... 기회가 된다면 이미지를 넣거나 할 수 있도록도 개선해보도록 합시다 !!
감사합니다 !

<img width="410" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/5b10bafc-6c51-4301-b6d9-501f7e984331">

**Comment by rbgus2002** [comment]
연동하시고 close issue 해주세요~! 
참고로 db 다시 살려놨습니다. 로컬에서 spring run 하시면 아마 안되실텐데 application.properties 수정해야 할겁니당 연락주세요~

**Comment by rbgus2002** [comment]
연동하시기 전에 확인해주셔야 할 부분이 있습니다!
해당 issue comment 확인해주시고 답변 주세요~!
https://github.com/rbgus2002/groupstudy/issues/21#issuecomment-1705203456

**Comment by Arkady1356** [comment]
넵넵 연동하고 이슈 추가로 날리도록 하겠습니다~
---
넵넵 두가지로 나눈 것으로 알고 진행하겠습니다
---
오호 좋습니다! 오히려 내심 원했던 방향입니다 굳굳

**Comment by rbgus2002** [comment]
> 넵넵 연동하고 이슈 추가로 날리도록 하겠습니다~
> 
> 넵넵 두가지로 나눈 것으로 알고 진행하겠습니다
> 
> 오호 좋습니다! 오히려 내심 원했던 방향입니다 굳굳

이전 이슈에서도 말씀드렸지만 GET /rounds/details에서 회차 약속 정보도 포함해서 response 하도록 수정 완료 했습니다!
