### ISSUE TITLE
사용자 별 스터디 색상 변경 API

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/groupstudy#23]
**_Description_**
> 스터디의 색상을 변경하는 API 개발
> 사용자는 스터디 마다 원하는 색상을 지정할 수 있다.

개발 완료했습니다. Request URL은 다음과 같습니다.
```
http://localhost:8080/studies/participants/colors?participantId=1&colorCode=0xFF
```

_Originally posted by @Arkady1356 in https://github.com/rbgus2002/groupstudy/issues/18#issuecomment-1666786961_

---
논의하고 싶은 부분이 있습니다 재우님~
스터디 처음 생성하는 경우에 어떻게 색상을 결정할지 정책 세우면 좋을 거 같아요.

개인적으로 생각한건 스터디 처음에 생성하는 경우, 플러터 단에서 랜덤으로 색상 코드 생성해서  request에 넣어주는 방법이 좋을 거 같긴합니다. 제가 말씀 드린대로 색상을 결정하는 경우에 스터디 생성 API의 request가 조금 수정될 거 같아요
현재는 아래와 같은데 colorCode를 추가하면 될 거 같습니다. 어떻게 생각하세욤
```json
{
  "studyName": "string",
  "detail": "string",
  "picture": "string",
  "hostUserId": 0
}
```

**Comment by rbgus2002** [comment]
언 제 해 줘 요

**Comment by Arkady1356** [comment]
헐 이건 언제보내셨던거죠 ㅋㅋㅋ 넵넵 좋습니다 Flutter 단에서 랜덤하게 생성해서 같이 보내드리도록 하겠습니다

**Comment by rbgus2002** [comment]
> 헐 이건 언제보내셨던거죠 ㅋㅋㅋ 넵넵 좋습니다 Flutter 단에서 랜덤하게 생성해서 같이 보내드리도록 하겠습니다

그러면 일단 [사용자 별 스터디 색상 변경 API] 붙여주시고 정상적으로 동작하는지 테스트 후에 알려주세요!
연동 완료 되면 [스터디 생성 API] 수정 후에 말씀 드리겠습니다!

**Comment by Arkady1356** [comment]
음 혹시 순서를 반대로 진행해도 괜찮을까요?

1. 스터디 생성 페이지 & API 제작
2. 스터디 수정 페이지 & API 제작 및 연결 (색상 변경 API 연결)
(이때 스터디 수정 페이지는 스터디 생성 페이지와 동일한 폼팩터 활용)

색상 변경을 스터디 수정 페이지에서 가능하도록 하는 것을 생각중에 있기 떄문입니다!!

**Comment by rbgus2002** [comment]
그럼요 그럼요 저도 찬성입니다! 그렇게 알고 있겠습니다!
