### ISSUE TITLE
공지 사항 상세 조회시 표시되는 댓글의 개수 issue

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#24]
<img width="214" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/710cf3c6-e250-4c02-a6b3-9f30007e69dd">

사진과 같이 삭제된 댓글을 포함한 개수가 반환됩니다!
API : get /notices

수정 부탁드립니다 ㅎㅎ

**Comment by rbgus2002** [comment]
현재 삭제된 comment는 count 하지 않도록 수정했습니다.
근데 대댓글이 존재하는 댓글 삭제하면 그냥 전체가 다 삭제되어 안보이게 되는데 에러인가요?

**Comment by rbgus2002** [comment]
또한 현재 삭제 버튼 누르면 바로 반영이 안되는데 해결해주세요 🫶🏽🥹

**Comment by Arkady1356** [comment]
오잉 저는 잘 작동합니다만 혹시 재현 가능하신가요??
<img width="378" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/0a402599-3d90-4a2c-8201-75df1aad4f30">


---
ㅋㅋㅋ.. 삭제 버튼 즉시 반영은 이전에 말한 것과 같이 조금 걸릴것 같습니다. 진행중에 있었으니 완료되면 차후 말씀드리겠습니다!!

**Comment by rbgus2002** [comment]
<img width="425" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/62997391/754e4e4c-1bac-48d9-9bab-c23c7e31c7cf">  

저는 다음과 같은 flow로 진행하였습니다.
1. 댓글 작성
2. 대댓글 작성
3. 댓글 삭제
4. 위에 사진과 같이 뜸

아예 대댓글 자체까지 안보이게 됩니다. 대댓글의 경우에는 삭제처리가 안되었기 때문에 전체 댓글 count에 포함되는 문제가 있습니다.

**Comment by rbgus2002** [comment]
> <img alt="image" width="405" src="https://user-images.githubusercontent.com/86937581/266014935-4027d4fc-0351-4a27-a1a3-a77ef9272157.png">
> pull 받기 전에는 위의 사진과 같이 잘 표시되었었습니다. 그러나, pull 받고 난 후엔 규현 님과 같은 현상이 보여지네요...
> 
> 추가로 확인해본 결과 댓글 API를 호출시 저 댓글("test")만 전달받습니다..! 확인부탁드립니다..ㅎㅎ

! 음 아예 API에서 잘못 줘버리는군요 ㅠㅠ 이따가 해결 후 comment 남기겠습니다

**Comment by rbgus2002** [comment]
1. 댓글 목록 불러오는 API 관련해서 버그 수정했습니다.
2. 공지사항 조회 시에 댓글 개수 정상적으로 세도록 버그 수정했습니다~!
