### ISSUE TITLE
할일 추가하기 및 수정하기 API 요청 

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#25]
안녕하세요 규현님!
이력서 작성이니 뭐니 하면서 정신이 하나도 없네요 하하

다름 아니라
새로운 Task의 작성과 Task의 수정을 위한 API를 요청 드립니다!
이때 작성의 경우에는

  1) 스터디 전체 할당
  2) 개인 할당

을 구별할 수 있어야합니다. 감사합니다.

**Comment by rbgus2002** [comment]
변경 사항 있습니다.
DELETE /tasks API에서 roundParticipantId를 추가하도록 변경했습니다. 서버 단에서도 추가적으로 본인의 task를 삭제하는지 검증하기 위함입니다.

**Comment by rbgus2002** [comment]
태스크 수정 API 개발 완료했습니다. [PATCH /tasks API]

**Comment by rbgus2002** [comment]
태스크는 기존에 제가 임의로 30자?까지 쓸 수 있도록 만들었는데 200자로 늘렸습니다. 괜찮으신가욤?

**Comment by rbgus2002** [comment]
> 이때 작성의 경우에는
> 1. 스터디 전체 할당
> 2. 개인 할당

센스쟁이 ~
태스크 생성 API 개발 완료했습니다. [POST /tasks API]
Group으로 type 설정 시에 해당 회차 참여자들 모두에게 태스크 할당됩니다
<img width="1417" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/62997391/f5abc3b2-2dad-4e60-8973-4664a198df66">

**Comment by Arkady1356** [comment]
> 태스크는 기존에 제가 임의로 30자?까지 쓸 수 있도록 만들었는데 200자로 늘렸습니다. 괜찮으신가욤?

넵 글자수 제한 확인하였습니다!

---
1. 규현님 새로 생성된 Task의 Taskid가 필요합니다 ! (수정 및 체크를 위해)
2. 추가로 체크 여부를 수정하는 API도 요청 드리겠습니다~

요청 API 리스트에도 추가해 놓도록 하겠습니다.

**Comment by rbgus2002** [comment]
> 1. 규현님 새로 생성된 Task의 Taskid가 필요합니다 ! (수정 및 체크를 위해)

PERSONAL task는 생성한 taskId를 return하면 되겠지만, GROUP은 어떻게 하면 좋을까요?

**Comment by rbgus2002** [comment]
> 2. 추가로 체크 여부를 수정하는 API도 요청 드리겠습니다~

개발 완료했습니다!

**Comment by Arkady1356** [comment]
> PERSONAL task는 생성한 taskId를 return하면 되겠지만, GROUP은 어떻게 하면 좋을까요?

group은 별도로 return 안해주셔도 저는 괜찮습니다! 
(task들을 관리하는 클래스가 관리해줌)

**Comment by rbgus2002** [comment]
> group은 별도로 return 안해주셔도 저는 괜찮습니다!

그러면 GROUP인 경우도 PERSONAL이랑 동일하게 본인이 생성한 task의 id return 하도록 하겠습니다~!

**Comment by rbgus2002** [comment]
> 1. 규현님 새로 생성된 Task의 Taskid가 필요합니다 ! (수정 및 체크를 위해)

1 부분도 개발 완료했습니다. 바로 위에 말씀드렸던 거랑 달리 GROUP인 경우는 null 반환하도록 했습니다. 스웨거에도 적어놨어욤

**Comment by Arkady1356** [comment]
아!!!!!!
소통이 잘못되었네요.... 

결과를 먼저 말씀 드리자면 taskType에 상관없이 taskId를 반환 받아야 합니다...


>> PERSONAL task는 생성한 taskId를 return하면 되겠지만, GROUP은 어떻게 하면 좋을까요?

> group은 별도로 return 안해주셔도 저는 괜찮습니다!

여기서 GROUP이 taskType이라고 생각하고 잘못 말씀을 드렸습니다.

1) 새로운 task의 taskId
2) 새로운 task의 taskType

을 반환해주신다고 이해하고
새로만든 taks의 taskType은 별도로 안주셔도 된다고 말씀 드렸던 것 이였습니다... ;ㅅ;
이동중에 확인한거라 꼼꼼히 확인하지 못했네요

taskType에 상관없이 taskId를 반환할 수 있도록 해주시면 감사하겠습니다...

**Comment by rbgus2002** [comment]
GROUP 타입의 task인 경우 회차에 참여하는 인원 n명 모두에게 task가 각각 할당되어 taskId가 n개 생기는데 배열 형태로 전달해드리면 되나요? 
GROUP 타입의 task인 경우에 taskId를 어떻게 드리면 될지 구체적으로 말씀해주시면 감사하겠습니다~~

**Comment by Arkady1356** [comment]
아하 taskId가 각각 생겨나는군요. 그렇다면 자신에게 할당된 taskId만 리턴받으면 됩니다.

**Comment by rbgus2002** [comment]
형식은 기존과 같습니다. GROUP 태스크 생성 시에 본인에게 할당된 taskId를 반환하도록 구현했습니다.

```json
{
  "success": true,
  "statusCode": 200,
  "message": "Success",
  "data": {
    "taskId": 50
  }
}
```
