### ISSUE TITLE
공지사항 목록 가져오기 관련 기능 개발 요청

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/groupstudy#26]
특정 스터디의 공지사항 목록을 조회할 때 강 공지사항 마다 작성되어있는 댓글 수를 볼 수 있으면 좋을 거 같습니다. 다음은 블라인드 어플의 경우는 다음과 같이 되어있습니다.

<img width="375" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/62997391/5f192612-f1a8-48b1-b517-46480dd5e663">

```json
...
"noticeList": [
      {
        "noticeId": 5,
        "title": "빈속에 커피를 마시면",
        "contents": "속이 쓰립니다.\n\n근데 밥먹고 커피를 마시다 보면 점점 배가 꺼지잖아요? 그러면 그건 빈속에 커피를 마시는 걸까요? 사실 지금 조금 속이 쓰립니다. 커피를 그만 마셔야 겠어요…",
        "writerNickname": "arkady",
        "pinYn": "Y",
        "createDate": "2023-09-08T17:51:35.764478",
        "commentCount": 3
      },
...
```

그래서 각 공지사항에 댓글 수를 확인할 수 있도록 `commentCount`를 추가하였습니다!
괜찮으시면 반영해주실 수 있으신가요 ㅎㅎ

**Comment by Arkady1356** [comment]
오 좋습니다 어디에 넣을진 또 고민해봐야겠네요

**Comment by rbgus2002** [comment]
오키 나머지 API도 연동해주세요~ 로그인 만들고 있을게욥

**Comment by Arkady1356** [comment]
규현님! 아래와 같이 해보았는데요,

<img width="334" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/8e1b42e9-9e38-41d5-947c-9957d9c1dff6">

이전에 이야기한 것 처럼 목록에서도 "확인 여부"를 알 수 있어야 한다는 점을 반영해서 왼쪽에 읽은 사람의 수를 표시해 보았습니다.
어떠실련지요 ㅎㅎ

만약 괜찮은 것 같으시다면 API에서 아래 두 가지를 추가로 전달해 주었으면 합니다!

1. 자신이 해당 공지를 확인 했는지 여부
2. 몇명이 해당 공지를 확인 했는지

감사합니다~

**Comment by rbgus2002** [comment]
오오 반영해주셔서 감사합니다!! 
좋은 의견인 거 같아요!! 1, 2번 모두 추가하고 말씀 드리겠습니다

**Comment by rbgus2002** [comment]
1, 2번 추가했습니다. 붙이면서 2번은 추후에 좀 더 디자인적으로 수정하면 좋겠다는 생각은 했는데 일단은 이렇게 가면 너무 좋을 거 같습니다!

[GET /notices/list] API에서 userId 파라미터가 추가 됐고, response에서 readCount와 read 필드가 추가되었습니다.
(아시겠지만, 로그인 붙이면 파라미터에 필요한 모든 userId는 삭제될 예정입니다.)

**Comment by Arkady1356** [comment]
어느정도 마음에 드셔서 다행입니다 =)ㅎㅎ

API는 문제 없이 잘 연결 되었습니다
(코드 작성할때 userId 변동을 고려했기 때문에 큰 문제 없을 것입니다 ㅎㅎ
나중에 로그인 구현이 끝나면 한번만 설명해주세요~ )

**Comment by Arkady1356** [comment]
공지사항 목록에서도 읽음 여부를 바꿀 수 있게 하는 것이 맞을까요? 아니면 공지 사항에 들어가서만 바꿀 수 있도록 해야할까요?

**Comment by rbgus2002** [comment]
> 공지사항 목록에서도 읽음 여부를 바꿀 수 있게 하는 것이 맞을까요? 아니면 공지 사항에 들어가서만 바꿀 수 있도록 해야할까요?

저는 개인적으로 공지사항의 상세 내용을 확인해야만 읽음 처리할 수 있게 만드는 것이 좋다 생각해서 후자가 좋은 거 같습니다!

**Comment by Arkady1356** [comment]
> 저는 개인적으로 공지사항의 상세 내용을 확인해야만 읽음 처리할 수 있게 만드는 것이 좋다 생각해서 후자가 좋은 거 같습니다!

헉 확인했습니다. 하지만 이미 기능을 만들어 버렸습니다 하하
일단은 말씀하신 것처럼 외부에서 확인 기능을 비활성화 시켜서 푸시하도록 하겠습니다!
