### ISSUE TITLE
할일 조회 API 수정 요청

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#30]
GET /tasks?roundId=

특정 회차의 모든 사용자의 할일을 조회하는 API에 수정을 요청드립니다.

현재는
1. roundParticipantId  (?? 뭔지를 몰라서 한글로 표현을 못하겠네요)
2. 유저아이디
3. [ 할일 리스트 ]

의 배열을 반환해 줍니다.
---

저희가 만들고자 하는 프로토타입은 다음과 같습니다.

<img width="430" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/931abbff-20cb-4d15-95ae-205917d2d6a9">

따라서
1. 사용자 닉네임
2. 해당 회차의 달성 정도
3. 참여 예정 여부 태그 { 참석, 늦참, 불참 ... } || 출석 상태 태그 { 지각, 출석 ... } 

가 추가로 필요합니다
감사합니다!

**Comment by rbgus2002** [comment]
해당 부분 구현 완료해서 다음과 같이 response 오도록 반영했습니다.
<img width="458" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/62997391/ebd25320-f9ce-4734-9e3a-5525274d80e1">

**Comment by rbgus2002** [comment]
재우님 질문있습니다
현재는 GROUP 선배치, PERSONAL 후배치하고 각각의 task 생성 순으로 정렬해서 response 해주는 중입니다.

flutter 단에서는 어떤 식으로 GROUP과 PERSONAL을 구분해서 아래 사진과 같이 보여주는지 궁금합니다.
제가 GROUP 선배치, PERSONAL 후배치 하는 의미가 딱히 없는 걸까요? 
(현재 todomate 처럼 완료처리 된 task는 맨 뒤로 보내도록 정렬 구현할까 고민 중이어서 여쭤봤습니다.)
<img width="164" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/62997391/d428de30-7d90-426a-9946-39ee2b7e96db">

**Comment by Arkady1356** [comment]
// 어제는 진짜 거짓말 안치고 학교 끝나고 집가자마자 잠든 기억도 없이 잠들어 버려서 하나도 못했네요 하하

response시 데이터 순서를 선배치 + 후배치 해주셨다는 의미시죠?
크게 상관이 없습니다.

지금의 제 프로그램 구조를 설명드리는게 더 좋을것 같네요

```Dart
// task.dart
class Task {
  int taskId;
  String detail;
  bool isDone;
}

// task_gourp.dart
class TaskGroup {
  int roundParticipantId;
  String taskType;

  List<Task> tasks;

  // add, remove, update에 관한 함수 호출하며 Tasks  관리
}
```

Json 데이터로 부터 객체를 만들 때에는 
1) taskType에 따라 Map 자료구조로 List<Task>를 만들고
2) 완성된 Map을 기준으로 TaskGroup 객체를 만드는 형식을 생각해 두었습니다.

솔직히 이거 안그래도 이슈 드릴까 했었는데
다음과 같은 형식으로 리턴해주시면 더 좋긴합니다..!
근데 그러면 데이터베이스 형식이랑 불일치해지는 것 같길래 별도로 요청은 안드리고 제 선에서 가공해서 사용하려 했습니다.

```json
"tasks": [
  {
    "roundParticipantId": 1,
    "statusTag": "NONE",
    "userId": 1,
    "nickName": "규규",
    "taskProgress": 0.7,
    "taskGroups": [
         {
             "taskType" : "GROUP",
             "tasks": [
                 {
                    "taskId": 16,
                    "doneYn": "Y",
                    "detail": "그룹태.."
                 }
                 ...
           ]
       },
       {
           "TaskType" : "PERSONAL",
           "tasks": [
                {
                    ...
                }
           ]
       }
   ]
}



``` 
혹시 이 방법은 어떠신가요 하하

이렇게 하면 완료된 task들에 대해서 정렬을 해도 위반되지 않고 좋을 것 같습니다 하하

이해 안되시거나 하시면 추가로 설명 드리겠습니다~

**Comment by rbgus2002** [comment]
> 혹시 이 방법은 어떠신가요 하하

약간 변형해서 다음과 같이 만들었습니다.

```json
{
  "success": true,
  "statusCode": 200,
  "message": "Success",
  "data": {
    "tasks": [
      {
        "roundParticipantId": 1,
        "statusTag": "NONE",
        "userId": 1,
        "nickName": "규규",
        "taskProgress": 0.7,
        "groupTasks": [
          {
            "taskId": 20,
            "doneYn": "N",
            "taskType": "GROUP",
            "detail": "string"
          },
          {
            "taskId": 16,
            "doneYn": "Y",
            "taskType": "GROUP",
            "detail": "그룹태스크 생성 테스트22222222222"
          }
        ],
        "personalTasks": [
          {
            "taskId": 18,
            "doneYn": "N",
            "taskType": "PERSONAL",
            "detail": "string"
          },
          {
            "taskId": 19,
            "doneYn": "N",
            "taskType": "PERSONAL",
            "detail": "야호"
          },
          {
            "taskId": 22,
            "doneYn": "Y",
            "taskType": "PERSONAL",
            "detail": "test"
          }
        ]
      },
      {
        "roundParticipantId": 2,
        "statusTag": "NONE",
        "userId": 2,
        "nickName": "arkady",
        "taskProgress": 0.7,
        "groupTasks": [
          {
            "taskId": 15,
            "doneYn": "N",
            "taskType": "GROUP",
            "detail": "그룹태스크 생성 테스트"
          },
          {
            "taskId": 35,
            "doneYn": "N",
            "taskType": "GROUP",
            "detail": "엥 리턴값이 null이야"
          }
        ],
        "personalTasks": []
      }
    ]
  }
}
```

> 정렬 기준 => (완료하지 않은 task 선배치, 완료한 task 후배치) AND task 생성 기준 오름차순

> 모든 회차 참여자는 groupTasks와 personalTasks를 갖고 값이 없는 경우 빈 list를 반환

**Comment by Arkady1356** [comment]
이것도 나쁘지 않은것 같습니다! 이대로 진행하겠습니다

**Comment by rbgus2002** [comment]
요청하신 형식으로 response 수정해서 배포했습니다 확인해주세요!
