### ISSUE TITLE
로그인 구현으로 인한 API 관련 수정 요청

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/groupstudy#31]
스프링 시큐리티를 활용해 자체 로그인을 구현했습니다. 
이에 따라 수정 및 추가된 API 목록은 여기다가 정리해놓겠습니다.

## To Do
**_추가_**
- [x] 로그인 API 생성 (/auth/signIn)

**_수정_**
- [x] 회원가입 API 경로 변경 (/auth/signUp)
- [x] 모든 API 앞에 /api를 prefix로 추가
- User API
    - [x] id를 통한 사용자 조회 => userId 인자 삭제
- Study Participant API
    - [x] 스터디에 회원 초대 => userId 인자 삭제
    - [x] 스터디에서 회원 초대 => API 경로 수정 (POST /api/studies/participants)
    - [x] 스터디에서 회원 탈퇴 => userId 인자 삭제
    - [x] 스터디에서 회원 탈퇴 => API 경로 수정 (DELETE /api/studies/participants)
- Study API
    - [x] 새로운 스터디 생성 => body 내 hostUserId 필드 삭제
- Round API
    - [x] 회차 삭제하기 => userId 인자 삭제
- Notice API
    - [x] 새로운 공지사항 생성 => body 내 userId 필드 삭제
    - [x] 공지사항 조회 => userId 인자 삭제
    - [x] 공지사항 읽음/안읽음 체크 => userId 인자 삭제
    - [x] 공지사항 목록 조회 => userId 인자 삭제
- Comment API
    - [x] 댓글 작성 => body 내 userId 필드 삭제
<br>

## What you need to know
> 로그인 및 회원가입을 제외한 나머지 API를 호출 할 때 request header 내 Authorization에 token을 담아서 호출하셔야 합니다! 
(이에 대한 개념과 관련해서는 [여기](https://reqbin.com/req/adf8b77i/authorization-bearer-header)를 참고해주세요)

> swagger 사용법 변경 (=> swagger 내에서 Header Authorization에 Bearer {token} 추가하는 방법)
>>    1. Auth의 [POST /auth/signIn] 호출을 통해 token 값 받아오기
>>    2. 스웨거 메인 페이지 상단 🔒Authorize 클릭 후 token 값 입력
>>    3. API 호출 가능

> /api/** API에 대해서는 호출하기 위해 USER 권한이 필요합니다.
> /auth/** API에 대해서는 호출하기 위해 권한이 필요하지 않습니다.

> JWT를 통해 로그인을 구현했습니다. 현재 토큰 만료 시간은 24시간이고 추후 협의를 통해 토큰 유효시간 정책을 결정하면 좋을 거 같습니다.

> ⭐️ 기존 최규현, 장재우의 계정 비밀번호는 0000 입니다.

**Comment by rbgus2002** [comment]
아직 push 안했습니다 참고만 해주세요~

**Comment by rbgus2002** [comment]
main branch에 배포 완료했습니다~

**Comment by rbgus2002** [comment]
일단은 이메일을 아이디로 사용하도록 구현했는데 이 부분에 대해서도 말해보면 좋겠네요..! 바로 동의 하시면 이메일 인증도 구현해보도록 하겠습니다

**Comment by Arkady1356** [comment]
헉 이메일 아이디 너무 좋은것 같아요 !!

**Comment by rbgus2002** [comment]
> 헉 이메일 아이디 너무 좋은것 같아요 !!

이메일 인증도 구현하면 좋을까요? 어떤 식으로 회원가입 시킬지 말해봐야 할 거 같습니다..!

**Comment by Arkady1356** [comment]
이메일 인증도 가능한가요?! 있으면 너무 좋을것 같습니다!!

아이디는 이메일 형식으로 fix하고 password는 길이 제약만 주고,
프로필 이미지 설정 가능하게 하고 프로필 메세지 설정 가능하게 하고... 흐음 다른게 뭐가 더 필요할까요

**Comment by rbgus2002** [comment]
> 이메일 인증도 가능한가요?! 있으면 너무 좋을것 같습니다!!
> 

구현해놓겠습니다~!


> 아이디는 이메일 형식으로 fix하고 password는 길이 제약만 주고,
> 
> 프로필 이미지 설정 가능하게 하고 프로필 메세지 설정 가능하게 하고... 흐음 다른게 뭐가 더 필요할까요

일단 그렇게만 하면 좋을 거 같습니다~!~!

**Comment by rbgus2002** [comment]
close 해도 되는걸까요?

**Comment by Arkady1356** [comment]
해당 이슈에서 다루는 이야기는 다 끝났지만

> 이메일 인증도 구현하면 좋을까요? 어떤 식으로 회원가입 시킬지 말해봐야 할 거 같습니다..!

이때 이 부분(이메일 인증)이 아직 안끝나서 close 안하고 있었습니다 ㅋㅋ 
이번에 새롭게 #39  가 추가 되었으니 해당 이슈는 close 하겠습니다~
