### ISSUE TITLE
홈 화면 관련 API 요청 

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#32]
안녕하세요 규현님!

홈 화면 관련 API를 요청드리기 위해 이슈 작성드립니다.
홈 화면은 다음과 같이 구성됩니다.

<img width="288" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/07ba3aea-7846-47a5-9c6b-53b1edb0ace2">

사용자의 아이디를 기준으로, 참여하고 있는 스터디에 대한 정보를 표시해주는데요,
각 스터디 별로 크게 3가지 정보가 필요합니다.

1. 스터디 정보
2. 회차 정보
3. 회차내 할일 정보

구체적인 내용은 아래 사진과 함께 첨부 드립니다! 

<img width="464" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/d4d25743-17e4-4dbc-8e8b-35b617277ca5">

**Comment by rbgus2002** [comment]
둘 중에 어떤 방법이 좋을까요?
1. 사용자가 가질 수 있는 스터디의 개수에 제한 두기
2. 사용자는 무한대로 스터디를 가질 수 있고, 홈화면에서 스터디 목록 받아오는데에 페이징 적용하기

**Comment by Arkady1356** [comment]
제한이 어느정도 넉넉하다면 전자가 좋을것 같아요!!
어느정도 제한을 생각중이신가요?

**Comment by rbgus2002** [comment]
> 제한이 어느정도 넉넉하다면 전자가 좋을것 같아요!! 어느정도 제한을 생각중이신가요?

사실 이 부분은 재우님이 훨씬 더 잘 알거라고 생각하는데, 그냥 근거없는 뇌피셜로 생각해보면 사용자 당 3개로 제한하고 프리미엄 회원(결제한 회원)은 20개까지 둘 수 있으면 좋겠습니당
프리미엄 부분 구현 전에는 사용자 당 10개로 제한하면 좋겠는데 참고만 해주세요. 이 부분은 재우님 의견 전적으로 따르고싶습니다~!

**Comment by rbgus2002** [comment]
참고로 너무 많은 스터디를 가지면 성능 저하가 많이 일어날겁니다! (아직 최적화 전이라 그런 것도 있음ㅋ.ㅋ)

**Comment by Arkady1356** [comment]
> 사용자 당 3개로 제한하고 프리미엄 회원(결제한 회원)은 20개까지 둘 수 있으면 좋겠습니당

캬하... 진짜 생각치도 못했는데요 ㅋㅋㅋ 저도 5~10개 기본 제약으로 생각해보고 있었습니다.
말씀하신것 처럼 나중에 유료화시에 개수 제한 높여주는거 너무 좋은것 같아요 !!!

우선은 10개로 할까요?

**Comment by rbgus2002** [comment]
좋습니다~!

**Comment by rbgus2002** [comment]
하나의 스터디에서 회차 약속 시간이 null인 회차는 2개 이상 만들 수 없고 오직 하나만 만들 수 있도록 하는 것이 어떤가요? 약속 시간이 null인 회차가 2개 이상 있으면 어떤 거를 우선적으로 가져와야 하는지 판단할 수 없습니다!

**Comment by Arkady1356** [comment]
roundId를 기준으로 우선적으로 하는것은 어떨까요?
2개 제약은 구현이 많이 복잡해질 것 같습니다..!!

*참고 : 현재 방식
1. \+ 버튼 누름 -> 빈 회차 생성(서버에 저장 안된 상태)(개수 제한 없음)
2. 장소 혹은 시간을 수정 -> 수정 감지 + 빈 회차 = 새로운 회차 생성 (서버에 저장)
3. 또 한번의 수정 -> 수정 감지 + 생성된 회차 = 회차 수정

**Comment by rbgus2002** [comment]
음 현재 방식 말씀해주신 건 이해를 못했습니다..!

> roundId를 기준으로 우선적으로 하는것은 어떨까요?

무조건 가장 최근에 생성된 걸 보여주자는 소리신건가요?? 맞다면 음.. 그게 사용자 입장에서 맞을지 모르겠습니다. 2개 제약은 서버 단에서 검증해도 됩니다!

**Comment by Arkady1356** [comment]
> 무조건 가장 최근에 생성된 걸 보여주자는 소리신건가요??

넵 맞습니다 !! 회차 추가 당시의 순서와도 일치해서 일관성있다고 생각됩니다

2개 제약은 서버단에서 검증을 하더라도, 현재 생성 방식과 불일치하기 때문에 적용이 어려울 것 같습니다..
음 생성 방식이 이해안되셨다 했는데,

1. 직접 체험해보기
2. 사진이랑 설명을 나열해서 설명드리기

어느쪽이 더 편하신가요..!

**Comment by rbgus2002** [comment]
> 어느쪽이 더 편하신가요..!

앗 제가 한 번 사용해보고 이해 안되면 다시 여쭤보겠습니다!
그러면 가장 최근거 보여주도록 구현해놓겠습니다!

**Comment by Arkady1356** [comment]
규현님!
홈 화면에서 할일 추가 삭제를 위해 roundParticipantId도 필요합니다!

**Comment by rbgus2002** [comment]
> 규현님! 홈 화면에서 할일 추가 삭제를 위해 roundParticipantId도 필요합니다!

roundParticipantId도 반영해서 홈화면 API 개발 완료했습니다~

**Comment by Arkady1356** [comment]
roundId도 주시면 감사하겠습니다..!!!

**Comment by rbgus2002** [comment]
회차가 존재하지 않는 스터디의 경우 roundSeq라는 회차의 횟수를 표현하는 필드를 0으로 주는 게 좋을까요 아니면 null로 주는 게 좋을까요?

**Comment by rbgus2002** [comment]
> roundId도 주시면 감사하겠습니다..!!!

추가했습니다~

**Comment by Arkady1356** [comment]
오호 안그래도 그 부분 생각해보았는데요, 1이 맞을 것 같습니다! 

> 추가했습니다~

선생님 진도가 너무 빨라욧~ 감사합니다ㅋㅋㅋ

**Comment by rbgus2002** [comment]
> 선생님 진도가 너무 빨라욧~ 감사합니다ㅋㅋㅋ

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ아 웃겨 ㅋㅋㅋㅋㅋㅌㅋㅌㅋ 학생~ 일어나~ 코딩해야지~

**Comment by Arkady1356** [comment]
ㅋㅋㅋㅋㅋ
교수님 추가적으로 요청드립니다!!

제공받는 회차의 우선순위가 변경 되어야합니다 !! (회차 리스트와 우선순위 다름)

1. 시간이 null이 아니면서 가장 가까운 시일 내의 미래의 회차
2. 시간이 null인 회차 (과거에 생성한 회차 우선)
3. 이미 시간이 지난 종료된 회차

**Comment by rbgus2002** [comment]
아 홈화면에서 보여주는 회차는 그렇겠군요.. 생각을 못했습니다.. 너무 복잡한데요? 흑흑......

정렬 기준 정리해놨는데 참고만 해주세요! 정리 안해놓으니까 매번 헷갈려서 기록해놨습니당
https://github.com/rbgus2002/groupstudy/wiki/Align-Standard

**Comment by Arkady1356** [comment]
ㅋㅋㅋ ㅋㅋㅋ 잘부탁드립니다 하하

헐 저 페이지 뭐로 그린거에요? 좋아보인다

**Comment by rbgus2002** [comment]
> ㅋㅋㅋ ㅋㅋㅋ 잘부탁드립니다 하하
> 
> 헐 저 페이지 뭐로 그린거에요? 좋아보인다

잘 쓰는 사람은 훨씬 더 예쁘게 잘 쓰더라구여.. https://excalidraw.com 입니다~

**Comment by rbgus2002** [comment]
> ㅋㅋㅋㅋㅋ 교수님 추가적으로 요청드립니다!!
> 
> 제공받는 회차의 우선순위가 변경 되어야합니다 !! (회차 리스트와 우선순위 다름)
> 
> 1. 시간이 null이 아니면서 가장 가까운 시일 내의 미래의 회차
> 2. 시간이 null인 회차 (과거에 생성한 회차 우선)
> 3. 이미 시간이 지난 종료된 회차

흑흑 너무 복잡했어요 완료했씁니다..

**Comment by rbgus2002** [comment]
연동 된거면 close 해도 될까요?!
