### ISSUE TITLE
할일과 관련한 API 수정 요청 리스트

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#34]
- [x] ~~1. POST /tasks : 태스크 생성~~
```Text
// 전달 인자
roundParticipantId,
taskType,
detail,

// 받길 원하는 결과
taskId,
```

- [x] ~~2. DELETE /tasks : 태스크 삭제~~
```Text
// 전달 인자
taskId,     // 이것 만으로 다른 사람 태스크까지 삭제할 수 있나..?
//roundParticipantId,
```
- [x] 3. PATCH /tasks : 태스크 수정
```Text
// 전달 인자
taskId,    // ~~이것 만으로 다른 사람 태스크까지 수정할 수 있나..?~~ -> 각자 수정으로 Fix
detail,
```

- [x] 4. PATCH /tasks/check : 태스크 수행 여부 변경
```Text
// 전달 인자
taskId
```

**Comment by Arkady1356** [comment]
3. PATCH /tasks : 태스크 수정
Group의 Task detail을 수정하면 다른 사람의 Task는 수정되지 않는 것 같습니다..!
확인 부탁드려요~

<img width="272" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/b8b0686f-0bee-4433-ab19-77d556c62d11">

**Comment by rbgus2002** [comment]
> 3. PATCH /tasks : 태스크 수정
>    Group의 Task detail을 수정하면 다른 사람의 Task는 수정되지 않는 것 같습니다..!
>    확인 부탁드려요~
> 
> <img alt="image" width="272" src="https://user-images.githubusercontent.com/86937581/270843536-b8b0686f-0bee-4433-ab19-77d556c62d11.png">
> <br> 음 아니면 Group Task는 수정 자체가 불가능하게 하는게 권한 측면에서 맞을까요 (아예 다시 삭제했다 등록만 가능하게?)

저는 다음과 같이 이해하고 있었습니다...!
GROUP 태스크 생성 => 회차의 참여자들에게 모두 GROUP TASK 할당
GROUP 태스크 삭제 => 본인의 GROUP 태스크만 삭제되고 다른 회차 참여자들은 계속 존재
GROUP 태스크 수정 => 본인의 GROUP 태스크만 수정되고 다른 회차 참여자들은 계속 존재

약간씩 각자의 것을 커스텀할 수 있어야 한다고 생각하는데 어떻게 생각하시나요?

**Comment by Arkady1356** [comment]
오 듣고보니 완전 맞는 말인 것 같아요!! 이렇게 진행하도록 하겠습니다~

**Comment by rbgus2002** [comment]
> 오 듣고보니 완전 맞는 말인 것 같아요!! 이렇게 진행하도록 하겠습니다~

감사합니다! 추가로 위에 적어주신 1,2,3,4번은 어떤 요청사항인가요?! 어떤거 요청해주신지 잘 모르겠어서 한번만 설명해주시면 감사하겠습니다~!

**Comment by Arkady1356** [comment]
1 ~ 4번은 API호출을 저 인자들 만으로 호출 할 수 있으면 좋겠다 싶어서 정리했던 것이였습니다.

1, 2번의 경우 본래 roundParticipantId를 없애고 싶었던 것이지만
이야기한 바와 같이 필수적인 요소여서 기존과 변화가 없음으로 무시하셔도 되고,

3, 4번의 경우에는, roundParticipantId 없이 taskId 만으로 변경할 수 있으면 좋겠다
싶은 것입니다 !!

**Comment by rbgus2002** [comment]
유효성 검증 때문에 받는 것이었는데, 쿼리 한 두번 더 날리면 없앨 수 있을 것 같습니다. 그러면 최적화는 나중에 신경쓰고 말씀해주신 대로 인자 삭제 후 진행하겠습니다!

**Comment by rbgus2002** [comment]
3,4번 모두 반영해서 배포했습니다!

**Comment by rbgus2002** [comment]
완료되면 close 해주십쇼~!!@!
