### ISSUE TITLE
프로필 상태 메세지 수정 API 연동 요청

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/groupstudy#40]
PUT /api/users/profile/messages
개발 완료했습니다! 연동 부탁드립니다.

**Comment by Arkady1356** [comment]
성공적으로 연동하였습니다.

현재는 홈 화면에서 프로필 메세지를 바로 수정할 수 있도록 하였습니다
<img width="360" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/9ce60652-0e58-4fd8-963f-488be8608702">
