### ISSUE TITLE
[홈 화면] 회차 표시 관련 에러 사항

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#44]
<img width="250" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/62b34385-b1ac-4e33-8780-e97552208478">

<img width="250" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/c62208c7-e314-471c-98fd-122a4067fc30">

사진과 같이 홈화면에서 7회차라고 표시되어 있지만
실제 내용은 전체 7개 중 3번째인 3회차의 내용입니다!

회차 번호가 잘못 표시되고 있습니다!!

**Comment by rbgus2002** [comment]
오 마이갓 낼 수정하겠습니다

**Comment by rbgus2002** [comment]
에러 수정했습니다.
수정하면서 새로운 에러를 ㅋㅋ 발견했습니다. 진짜 개억까인게 이거 mysql 버그 같은데 분명 제 무지함 때문이겠죠?
가끔씩 (아직 원인도 모르겠습니다) 회차 약속시간이 정해지지 않은 회차가 2개 이상 있을 때 잘못된 순서의 회차를 가져오는 경우가 있습니다. 일단은 이거 주석에 달아놨는데 나중에 앱 다 만들고 수정하시죠..... 흑흑

**Comment by rbgus2002** [comment]
확인해주시고 issue close 해주시면 감사하겠습니다

**Comment by rbgus2002** [comment]
댓글 삭제하기 웨안됌

**Comment by Arkady1356** [comment]
ㅋㅋㅋㅋ 확인하였습니다~

---

?? 네 ?? 확인해보고 말씀 드리겠습니다...
=> 예물레이터 업데이트 이슈로 확인이 늦어질 예정입니다 하하 ~

---

API 호출 URL에 오타가 있었습니다.. 하하
한번 다시 Pull 받고 해보시겠어요?
저는 예물레이터가 아직 업데이트인 관계로 확인은 못해봤습니다..!
