### ISSUE TITLE
[B] spring boot version 변경

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/groupstudy#5]
_변경 전 spring boot version -> 3.0.5
변경 후 spring boot version -> 2.7.11
변경 전 jdk -> 17
변경 후 jdk -> 11_

변경한 이유는 다음과 같습니다.
1. spring boot의 version이 3.0으로 업그레이드 됨에 따라 spring security, swagger 등에서 설정 방식이 다소 달라졌습니다. 하지만 공식문서 조차 이에 대한 반영이 잘 안되어 있으며, 참고할 수 있는 레퍼런스가 매우 적습니다.
2. spring boot 3.0이 정식 release 됐음에도 불안정한 요소가 존재한다고 합니다.

위와 같은 이유들로 인해 version downgrade를 진행했습니다. 참고 부탁드립니다.

**Comment by rbgus2002** [comment]
@Arkady1356 
참고로 프로젝트 내에서 jdk version은 직접 11로 변경해주셔야 합니다~!

**Comment by Arkady1356** [comment]
넵 확인하였습니다. 말씀하신 대로 설정해두도록 하겠습니다 =)
