### ISSUE TITLE
[F] feat : NULL 처리에 대한 논의

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#69]
하하 제가 전에 프로필 이미지를 등록하지 않았을때 (== 프로필 이미지가 없을때)
NULL 값이여도 상관없다고 무의식중에 말한것 같은데요...

코드를 추가적으로 작성하다 보니 NULL보다 ""이 더 완성도 높은 결과물을 만들 수 있을것 같습니다... 하하
그래서 혹시 모든 String 타입의 NULL을 ""로 처리해주실 수 있나요?

회원 정보, 스터디 정보, 회차 등 모두가 대상입니다
수정이 많아질까요..

## 🐌 Summary
String 타입의 NULL을 모두 ""로 바꿔주세요

## 📝 To Do List
- [ ]  (String)NULL -> ""

**Comment by rbgus2002** [comment]
음..! 수정할 부분이 많지는 않은 거 같습니다. 근데 값이 없는데 빈문자열인 ""로 넣는 것이 조금 어색하다고 느껴져서 null이 맞지 않나 싶은데 어떻게 생각하시나요? 
굳이 값 자체가 들어가지 않아도 되는 칼럼에 대해서도 빈문자열이 들어가는 경우에 공간적으로 낭비가 아닌가 싶기도 합니다..!
(본문에 말씀하신 완성도 높은 결과물이라 표현하신 건 코드의 가독성면에서 일까요?)

**Comment by Arkady1356** [comment]
> (�본문에 말씀하신 완성도 높은 결과물이라 표현하신 건 코드의 가독성면에서 일까요?)
``` dart
    String picture; // not null
    ...
    return User(
        ...
        picture: json['picture']??"", 
    );
```
위의 코드가 예시인데요,
A??B 문법은 A가 NULL이면 B를 넣는 문법입니다.

저는 이 문법이 지저분한 느낌을 주고,
짜피 NULL이면 ""넣어야 할거 서버에서 부터 ""로 주면 좋겠다~ 싶었던 것입니다!

위처럼 작성하지 않고 NULL을 허용하면,
1. if (str != NULL && str.isNotEmpty)
과 같이 2번에 걸쳐서 검사해야하는 문제가 생기고 

2. str!
과 같이 사용시 A가 NULL이 아님을 보장하는 문법 A!를 사용해야하는 번거로움이 있습니다.

---

이러한 이유였는데,
> 굳이 값 자체가 들어가지 않아도 되는 칼럼에 대해서도 빈문자열이 들어가는 경우에 공간적으로 낭비가 아닌가 싶기도 합니다..!

이 말이 맞는 말인것 같습니다..

=> 기존처럼 NULL로 전달 받는 걸로 하겠습니다!

--- 
추가로 생성 및 가입 API 호출시에 저는 
빈 값에 ""를 전송하는 것으로 했었는데
서버에서 처리를 해주나요? 아니면 전송할때 NULL로 변환해서 드려야할까요?

**Comment by rbgus2002** [comment]
감사합니다!!

혹시 생성 및 가입 API가 어떤 것이죠?! 어떤 인자를 ""로 전송해주셨는지 말씀해주시면 한 번 checkcheck 해보겠습니다!

**Comment by Arkady1356** [comment]
음 당장 생각나는 예시로는 회원가입시에 프로필 이미지가 없으면 ""를 전달했던 것으로 기억합니다!

**Comment by rbgus2002** [comment]
1. 일단 스터디 생성 시에 picture는 임시로 박아둔 값이고 현재 구현은 안되어있습니다. 내일 File을 인자로 받을 수 있도록 수정해놓겠습니다!

2. 어제 요청해주셔서 회원가입 시에 프로필 사진 입력받을 수 있도록 추가했는데 해당 부분은 null인지 아닌지 체크합니다!
의식적으로  null값이 올 수 있는 경우에는 처리를 해두었긴 합니다.

**Comment by rbgus2002** [comment]
해당 이슈 close 하겠습니다!
