### ISSUE TITLE
[B] Notice와 관련된 API에 대한 Issue

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#7]
안녕하세요 규현님,

해당 Issue는 Notice 기능과 관련된 API에 대한 세부사항 조정을 위한 Issue입니다.

---
1. /notices/list | 공지사항 목록 가져오기 : Notice Id 필요
  각 Notice Summary의 Notice Id또한 전달이 필요합니다.
  해당 Notice Id를 통해 Notice 상세 보기로 접근하기 위해 필요합니다.

**Comment by rbgus2002** [comment]
혹시 번역기를 돌리셨나요?

**Comment by rbgus2002** [comment]
[/notices/list] 공지사항 목록 가져오기 API를 다음과 같이 수정했습니다.

1. 상단고정이 되어있는 공지사항을 우선적으로 가져오도록 수정하였습니다.
2. 공지사항 생성 시각 기준 최신순으로 가져오도록 수정하였습니다.
3. 요청하신 대로 noticeId도 함께 response 하도록 수정했습니다.
4. 상단 고정이 되어있는 공지사항인지 구분할 수 있도록 pinYn도 함께 response 하도록 수정했습니다.

~~~~~

**Comment by Arkady1356** [comment]
2. /notices | 공지사항 작성하기 : Notice Id 필요
 게시물을 작성하면 해당 게시물이 열리기 위해선 Notice Id가 필요합니다

3. /notices | 공지사항 작성하기 : Cotents의 최대 길이
 내용의 최대 길이가 좀 많이 짧네요..!! 참고로 제가 예시로 작성해보았던 게시물이 360자 정도였습니다(현재 100자). 구체적인 숫자는 나중에 정하더라도 인지는 하셔야할것 같아서 말씀드려요 =)

**Comment by rbgus2002** [comment]
2. 현재는 공지사항 작성하면 success 여부에 대해서 response를 해주고 있습니다. success 여부와 더불어 noticeId도 같이 response 해달라는 말이신가요?

3. 추후에 최대 길이에 대해서 얘기해보면 좋을 거 같습니다. 알고만 있겠습니다~

4. 현재 요청해주신대로 writerNickname으로 response 해주고 있습니다. 어떤 부분 확인해달라는 건지 좀 더 구체적으로 말씀해주세요!

**Comment by Arkady1356** [comment]
2. 네 정확합니다 !!
3. 넵!!
4. DataGrip에서 
id | Name | Nickname
1 | 장재우 | hi
2 | 최규현 | 규규
로 저장이 되어있는데, response로 받은 내용이 장재우 최규현입니다..! 사진도 첨부해 드릴게요
<img width="389" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/41ab6800-78c8-4ff9-b2cc-18e3a9cb4729">

**Comment by rbgus2002** [comment]
2. noticeId 포함해서 reponse 하도록 수정해서 반영 완료했습니다.
4. 그러네요 ㅎㅎ 닉네임이 아닌 이름을 get 해왔네요... 수정했습니다~!~!

issue close 하겠습니다. 많이 많이 요청해주세요 저를 괴롭혀주세요 어서 API 요청해
