### ISSUE TITLE
[B] User Profile과 관련된 API에 대한 Issue

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#8]
안녕하세요 규현님,

해당 Issue는 User Profile 기능과 관련된 API에 대한 세부사항 조정을 위한 Issue입니다.

이야기에 앞서 Profile에서는 3가지 유형이 있습니다. 명칭 정의하고 시작하겠습니다.
1. User Profile Summary : 이미지, 이름, 상태 메세지를 가진 요약 프로필
2. User Profile (Detail) : 위의 내용과 더불어 참여하고 있는 스터디, 출석률 등을 보여줌
3. User Profile Image : 참여자 리스트 등을 보여줄때 보여줄 이미지 프로필 

---
1. ?? | User Profile Image가 필요합니다.
이때 세부적으로 User Profile Image는 다음과 같은 정보를 전달합니다.
(1) userId : 클릭시 세부 정보 조회로 넘어갈 수 있습니다.(?아닌가?)
(2) image : 표시될 이미지입니다 이때 스케일이 작은 이미지이긴 하나 이것은 나중에 다루도록 합니다.
(3) color : 참석 여부, 혹은 진행도를 표시하기 위해 표시될 색상 정보를 가지고 있어야합니다.
(4) progress : 진행도를 표시하기 위한 [0:1.0]의 값을 가지는 값이 필요합니다. 특별히 사용하지 않는 경우에는 1.0을 리턴해주시면 감사하겠습니다.

**Comment by rbgus2002** [comment]
요청하신 User Profile Image는 스터디 상세페이지에서 회차 목록 안에서 보여지는 내용인가요?

**Comment by Arkady1356** [comment]
<img width="382" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/cebee673-b078-4529-b75b-b7f3a2568856">
다음 이미지와 같이 유저 리스트들을 보여줄때 이용됩니다 =)

**Comment by rbgus2002** [comment]
카톡에서 의논한대로 스터디 상세 페이지에 있는 MEMBER 목록 반환하는 API부터 개발 시작할게요~

**Comment by rbgus2002** [comment]
요청해주신 부분 개발 완료해서 배포했습니다. (/studies/participants/summary)
가입 시각 기준 오름차순 정렬해서 스터디에 소속된 사용자의 프로필 이미지와 userId 리턴해줍니다~
