### ISSUE TITLE
[B] feat : 공지사항 목록 조회 API 내 writerId 추가 반영 요청

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/groupstudy#80]
## 🐌 Summary
[GET /api/notices/list] API에 writerId 추가~

## 📝 To Do List
- [ ]  writerId 반영 요청

## 📷 스크린샷(선택)
<img width="1379" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/62997391/fcf40fc7-25c0-421b-8612-4674c6670d0d">

**Comment by Arkady1356** [comment]
규현님 추가 수정 요청드립니다!

두개의 API의 
"읽은 사람 수"
의 인자 명을 통일 시켜주세요

GET /api/notices/list 에선 "readCount"
GET /api/notices 에선 "checkNoticeCount"

라서 재사용성을 높일 수가 없네요!!!

**Comment by rbgus2002** [comment]
앗.. 죄송합니다 ㅎㅎ readCount로 통일하여 반영 완료했습니다 ㅎㅎ
