### ISSUE TITLE
[B] Comment 댓글과 관련된 API에 대한 Issue

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#9]
안녕하세요 규현님,

해당 Issue는 공지 사항 상세 보기에서의 Comment 기능과 관련된 API에 대한 세부사항 조정을 위한 Issue입니다.

---
1. 대댓글 기능의 구현
대댓글 기능 구현을 위한 이야기를 나눠보면 좋을것 같아요.
DB에서는 댓글이 부모 댓글을 가질 수 있도록 하여 대댓글 관계를 표현한 것을 확인하였습니다. 이때 Front에서 comments를 가져오는 API를 호출하면 어떤식으로 리턴받을지를 생각해봐야할것 같아요.
제가 생각해본 것은 두가지 입니다.
(1) Comment는 replies라는 이름의 List<Comment>를 가지도록 하는것 입니다. 예시를 하단에 첨부하겠습니다. 
(2) Comment는 isRepy라는 bool값을 가지고, 해당 값에 따라 일반 댓글 UI와 답글의 UI로 달라보이도록 구현하는 것입니다.

(1)의 예시
<img width="353" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/b01822a1-e17e-48ac-90a6-b713e245344f">

(2)의 예시
<img width="373" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/43a8851e-7e2f-4e53-bbb5-300ad4310f79">

결과 
<img width="451" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/02211a5a-6b94-4f2c-bcea-eabba28a6f51">

**Comment by rbgus2002** [comment]
(이 와중에 예시로 만들어놓은 내용 너무 웃기네요............ㅋㅋㅋㅋㅋ)
저는 재우님이 생각하신 (1)이 백번 맞다고 생각합니다. (2)는 뭔가 어색하고 이상해욥. (1)처럼 구현하면 좋을 거 같은데 어떻게 생각하시나요?

**Comment by rbgus2002** [comment]
1. 앞으로 add feature은 (기획에 대한 논의가 거의 끝난 상태에서) 신규 기능 개발을 요청할 때 Label 달면 좋을 거 같습니다! 

2. 해당 issue 처럼 기획에 대한 논의는 discussion Label을 활용하면 좋을 거 같은데 어떻게 생각하시나요? 방금 만든 Label 입니다 ㅋㅋ

3. 제목은 ~ 관련 issue 보다 조금 더 구체적으로 작성하면 추후에 확인할 때도 더 좋을 거 같네요. 예를 들면 해당 issue는 "공지사항에서 대댓글 response 형식에 관한 의견 논의"가 더 좋겠습니다. 

4. (어제 말씀 드린 부분에 덧붙여서 하나만 더 말씀 드리고싶은 게 있습니다!) 제목에 Comment 댓글과 관련된 ~ 라고 적어주셨는데 굳이 Comment와 같은 변수명?까지 적어주실 필요는 없다고 생각합니다. 사용하시는 게 편하시다면 위 제목보다는 차라리 "Notice 댓글과 관련된 ~ " 이 더 적합한 거 같습니다!

**Comment by rbgus2002** [comment]
다시 읽어보니 제가 너무 까다로운가 싶네요.. ㅠㅠ 구현 초기 단계인 만큼 처음에 의견 조율 잘 햄놓으면 좋을 거 같아서 말씀드렸습니다 ㅎㅎ

**Comment by Arkady1356** [comment]
ㅋㅋㅋ 잘 읽어봤습니다
1. 넵넵 !!
2. 오 dicussion 좋은 것 같아요!!
3. 제목은 일부러 큰범위로 작성했던것 이였습니다. 저는 지금까지 하나의 범주 단위로 발생할 수 있는 이슈들을 묶어서 하나의 이슈에서 처리하려고 의도하였습니다. (공지, 댓글, 태스크, 등등)   이러한 의도가 잘 전달되지 않았나 보군요. 그럼 말씀하신 것처럼 각각을 나누어서 이슈를 보내면 될까요? (지금까지 작성된 이슈들 내용에서 1 2 3 에 해당하는 것들이 각각의 이슈로 작성되는 것을 의미합니다.) 근데 이렇게 되면 나중에 검색하기가 어려워질 수도 있으니 이러하 범주(공지, 댓글, 태스크 등)도 label로 만들어서 달으면 좋을까요?
4. 오 저건 진짜 무의식중에 그냥 Comment라고 영어로 적고 나중에 헷갈리실까봐 댓글이라고 추가해 것이였습니다 ㅋㅋ. 넵 제목 작성에 더 신경쓰도록 하겠습니다.

**Comment by rbgus2002** [comment]
3. 아하 그런 의도였군요ㅋㅋㅋ 말씀하신 하나의 범주 단위에도 다양한 이슈가 발생할 수 있기 때문에 시간이 지나면 오히려 원하는 정보 찾기가 어려울 수도 있을 거 같습니당 생각해보니 범주 또한 label로 만들면 그게 최선일 거 같습니다 굳굳

**Comment by rbgus2002** [comment]
댓글 작성 API 구현 완료했습니다.
댓글 조회 API는 대댓글 제외하고 구현 완료했습니다,

**Comment by Arkady1356** [comment]
안녕하세요 규현님! 
비가 많이 오는 밤이네요

1. 새로운 댓글 작성시 대댓글을 작성하는 경우, 부모 댓글의 아이디를 가져야하는데(전달해야하는데) 그런 부분이 아직 반영되지 않은 것 같아요!
댓글 조회의 경우에도 부모 댓글의 아이디를 함께 전달해주셔야한 다는 사실 참고 부탁드립니다!

**Comment by rbgus2002** [comment]
댓글 작성에서 대댓글 기능 구현 했습니다. 스웨거에서 [POST /comments] description 확인해주세요!

댓글 조회에서 대댓글 기능 구현하고 다시 말씀 드리겠습니다.

**Comment by Arkady1356** [comment]
규현님! 해당 기능이 완성되었을 때 댓글의 작성 가능한 최대 길이도 알려주시면 감사하겠습니다 =)

**Comment by rbgus2002** [comment]
댓글 조회에서 대댓글 기능 구현 완료했습니다!

**Comment by rbgus2002** [comment]
댓글 작성 가능한 최대 길이는 협의가 필요할 거 같습니다.
