### ISSUE TITLE
[F] feat : 공지 생성 API 수정 요청 

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#90]
현재는 새로운 공지의 noticeId를 반환해주는데요,
이번에 공지 조회 방식을 수정하게 되면서

1. 공지 생성 API -> 새로운 noticeId 
2. 새로운 noticeId -> 공지사항 조회 API -> 공지사항 정보 획득
3. 공지사항 정보 -> 공지사항 상세 조회 페이지로 이동

의 과정을 거치는데요,
요약 하자면 API를 2번씩 호출하는 불편함이 있다고 생각됩니다.

이에
새로운 공지사항 생성시
새로운 공지사항의 모든 정보를 주실 수 있나요?

## 🐌 Summary
새로운 공지사항 생성시 생성된 공지사항 전체를 전달해 주세요
POST /api/notices/

## 📝 To Do List
- [x]  새로운 공지 생성시 생성된 공자사항을 리턴하도록 수정

**Comment by rbgus2002** [comment]
반영 완료했습니다!
