### ISSUE TITLE
[F] feat : 참여자 프로필 상세 보기 수정 요청 

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#91]
GET /api/studies/participants에 다음의 수정 사항을 요청 드립니다!

## 🐌 Summary
GET /api/studies/participants
1. 프로필 이미지 누락
2. 스터디 컬러 필요 => { 스터디 이름 + 스터디 컬러 }의 리스트
3. 닉네임이 있었는데 없어진것 같습니다!
---
4. 스터디 프로필 이미지가 필요합니다

## 📝 To Do List
- [x] 프로필 이미지를 추가해주세요
- [x] 스터디 컬러를 리스트에 추가해 주세요
- [x] 닉네임을 추가해주세요
- [x] 스터디 프로필 이미지를 추가해주세요

**Comment by rbgus2002** [comment]
구현 완료했습니다!

**Comment by rbgus2002** [comment]
(접때 어렴풋이 스터디 생성하면 회차를 하나 디폴트로 만들어달라고 하셨던 거 같은데 이슈로 요청 부탁드립니다!)

**Comment by Arkady1356** [comment]
nickname이 누락되어서 추가로 요청드립니다!

**Comment by rbgus2002** [comment]
nickname 포함시켰습니다..!!

**Comment by Arkady1356** [comment]
질문이 있습니다!
API를 호출하려보니 studyId가 걸립니다

사용자 프로필을 조회할때 studyId가 필수인가요?
출석률 및 과제 완수율이 해당 스터디에 국한된 정보일까요!?

제가 생각했던 프로필 조회는
사용자의 모든 스터디에 대한 데이터 통계를 생각했긴 합니다!

**Comment by Arkady1356** [comment]
추가로 스터디 프로필 이미지가 필요합니다!
이게 필요한걸 지금 봤네요.. 하하

**Comment by rbgus2002** [comment]
> 질문이 있습니다! API를 호출하려보니 studyId가 걸립니다
> 
> 사용자 프로필을 조회할때 studyId가 필수인가요? 출석률 및 과제 완수율이 해당 스터디에 국한된 정보일까요!?
> 
> 제가 생각했던 프로필 조회는 사용자의 모든 스터디에 대한 데이터 통계를 생각했긴 합니다!

현재 스터디에 대한 정보를 조회해야 해서 필요합니다! 

처음에 모든 스터디에 대한 데이터 통계로 말씀 나눴다가, 이후에 다시 말씀 나눴을 때 현재 스터디에 대한 데이터 통계를 보여주자고 한 게 기억나서 이렇게 구현해놨습니다!! 
저는 스터디마다 성격이 다를 수 있기 때문에 모든 스터디에 대한 데이터 통계를 보여주는 게 크게 의미가 없다고 생각합니다..!  그래서 지금처럼 현재 스터디에 대한 정보가 맞지 않나 싶은데 어떻게 생각하시나요? (추후에 소속된 스터디 목록을 클릭하면 해당 스터디에 대한 데이터 통계를 보여주도록 추가 기능을 만들고싶은 생각도 있습니다..!)

**Comment by rbgus2002** [comment]
> 추가로 스터디 프로필 이미지가 필요합니다! 이게 필요한걸 지금 봤네요.. 하하

앗 저도 놓쳤네요 ㅠㅠ studyColorInfo에서 participantInfo로 변경했고 해당 리스트 안에 넣어두어 반영했습니다!

**Comment by Arkady1356** [comment]
> 저는 스터디마다 성격이 다를 수 있기 때문에 모든 스터디에 대한 데이터 통계를 보여주는 게 크게 의미가 없다고 생각합니다..! 

확실히 유의미한 통계가 되기 위해선 스터디에 대한 통계를 조회하는게 맞을 것 같네요
이렇게 인지하고 개발하도록 하겠습니다 !!

**Comment by rbgus2002** [comment]
> > 저는 스터디마다 성격이 다를 수 있기 때문에 모든 스터디에 대한 데이터 통계를 보여주는 게 크게 의미가 없다고 생각합니다..!
> 
> 확실히 유의미한 통계가 되기 위해선 스터디에 대한 통계를 조회하는게 맞을 것 같네요 이렇게 인지하고 개발하도록 하겠습니다 !!

네네넵 요청하신 건은 모두 반영해놓았습니다!

**Comment by rbgus2002** [comment]
모두 반영된 건 이면 close 부탁드립니다!!
