### ISSUE TITLE
[F] bugfix : 홈 화면 장소 미정 오류 검토 요청

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/groupstudy#94]
## 🐌 Summary
로그 확인 결과 장소가 null 값이 아닌 경우 스터디 약속 장소를 잘 reponse 해주는 것으로 확인했습니다!
혹시 프론트 단에서 오류는 아닐지 검토 부탁드립니다!

## 📝 To Do List
- [x]  장소 미정 오류 검토 요청

**Comment by Arkady1356** [comment]
으악 if문 순서를 반대로 했었네요 하하
수정하였습니다~

추가로 이전에 이야기한것 처럼 장소가 길어질 경우 스크롤 되도록 하였습니다 (홈화면만)
(아직 공지사항 세부조회 부분은 반영하지 않음)
