### ISSUE TITLE
[F] feat : 스터디 생성시 기본 회차 추가 요청

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/groupstudy#95]
새로운 스터디를 생성하였을때
기본적으로 하나의 회차가 생성되었으면 합니다

아래의 스크린샷에 Todomate에서 처음 시작하였을 당시
기본적으로 3개의 목표가 생성되어 있는 것을 확인하실 수 있습니다.

이를 통해 사용자의 사용을 유도할 수 있을 것이라 생각합니다

## 🐌 Summary
POST /api/studies/
새로운 스터디 생성시 기본 회차를 생성해주세요

## 📝 To Do List
- [x]  스터디 생성 -> 기본 회차 생성

## 📷 스크린샷(선택)
<img width="591" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/f6316985-dd59-4987-8dc4-9c381873a3b4">

**Comment by rbgus2002** [comment]
구현 완료해서 배포했습니다!

**Comment by rbgus2002** [comment]
임의로 강남역 스타벅스, 3일 뒤 약속시간으로 픽스해서 기본 회차 생성합니다!

**Comment by rbgus2002** [comment]
접때 말한 이유가 오로지 사용자의 유도만 있었던 건 아니었던 걸로 기억합니다.

버그 관련해서도 이슈가 있었던 거 같은데 혹시 설명해주실 수 있나요? 
현재 홈화면을 불러오는 API에서 버그를 수정 중인데 이유를 알아야 결정할 수 있는 부분이 있어 여쭤봤습니다.!

**Comment by Arkady1356** [comment]
!!
저는 아래 사진과 같이 생각했습니다

장소 : 미정 (null)
시간 : 미정 (null)
그룹 과제, 
개인 과제에 각각 하나의 과제가 임시로 추가된 것을 생각했습니다

하하 늦게 답변 드려서 죄송합니다...

![image](https://github.com/rbgus2002/groupstudy/assets/86937581/e160a3e6-05a5-431a-9f71-0be9bcd91081)

**Comment by rbgus2002** [comment]
앗!! 말씀하신 대로 수정해서 반영해놓겠습니다!

**Comment by rbgus2002** [comment]
재우님 궁금한 점 있습니다. 현재 서버에서 정상이 아닌 예외 코드 (400, 404, 500 등)을 보내는 경우에는 서버에서 보내주는 메세지 그대로 사용자에게 보여주도록 예외처리가 되어있나요?

**Comment by Arkady1356** [comment]
넵 대부분은 그렇게 되어있습니다
초기에 API를 접목한 부분은 일부가 안되어 있는 것으로 기억하고,
최근에 연결한 API는 각자 적합한 형태로 사용자에게 보여지도록 되어있습니다 !

**Comment by rbgus2002** [comment]
> 넵 대부분은 그렇게 되어있습니다 초기에 API를 접목한 부분은 일부가 예외처리 및 보여지도록 안되어 있는 것으로 기억하고, 최근에 연결한 API는 각자 적합한 형태로 사용자에게 보여지도록 되어있습니다 !

아하 알겠습니다!

**Comment by rbgus2002** [comment]
> 넵 대부분은 그렇게 되어있습니다 초기에 API를 접목한 부분은 일부가 예외처리 및 보여지도록 안되어 있는 것으로 기억하고, 최근에 연결한 API는 각자 적합한 형태로 사용자에게 보여지도록 되어있습니다 !

지금 구현 완료해서 기본 과제 생성하도록 만들어놨는데 궁금한 점 있습니다!
현재 스터디 페이지를 불러오기 위해서 3개 정도 API를 호출하는 걸로 알고있는데 스터디가 삭제되어있는 경우는 어떤 식으로 삭제되었다고 알려주나요? (공지사항도 마찬가지입니다.)
1. 홈화면에서 스터디 상세 페이지를 가기 위해 스터디를 클릭한다.
2. 스터디를 불러오기 위해 3개의 API를 호출한다 (스터디 요약 API, 멤버 목록 조회 API, 회차 목록 조회 API)
3. 셋 중 하나의 API에서 404(스터디가 존재하지 않습니다) response를 주면 스터디가 존재하지 않는다고 응답받으면 홈화면으로 다시 돌아간다.
이런 흐름인가요?

**Comment by Arkady1356** [comment]
오호 !! 스터디 삭제를 아직 안붙여서 생각해보지 못한 문제이네요

제가 만약 구현했다면,
3개의 API 모두를 고려하기 보다는
스터디 요약 정보를 불러오는 API(최상단에 위치한 위젯)를 통해서 존재 여부를 확인할 것 같아요!

아직 존재하지 않는 스터디에 대한 접근의 오류 표출? 표시??를 안해두었습니다.
위에 말한 방식대로 해도 괜찮을까요!!

**Comment by rbgus2002** [comment]
아주 좋은 거 같습니다! 감사합니다~! 반영 완료해서 issue close 해놓겠습니다!
